const { Building } = require('../models')

const buildingData = [
    {
        name: "Basilikoi Paides",
        icon: "../imgs/Basilikoi_Paides.webp",
        description: "The basilikoi paides (roughly “royal page school”) was a long-held tradition in Macedon, but Philip II transformed it into a powerful tool to advance the needs of both king and state. Macedon’s noble sons, as well as those the king deemed worthy, were admitted to the basilikoi paides—a prestigious manner of dealing with royal hostages. Philip spared no expense in hiring the finest tutors, including renowned philosopher Aristotle, who likened the basilikoi paides to a “school for generals.” Indeed, beyond the arts of war and administration, the young pages were taught to honor and obey the king, to protect him with their lives, and to serve Macedon’s interests above all others. This helped forge national bonds that superseded familial ties, in turn reducing chances of rebellion among the nobility. Graduates were afforded a position of prominence within the hetairoi (Companion cavalry). Alexander continued the tradition after his father’s death.",
        ability: "+1 Production +1 Housing +1 Citizen slot +1 Great General point per turn +25% combat experience for all melee, ranged, anti-cavalry land units, and Hetairoi trained in this city. Gain Science equal to 25% of the unit's cost when a non-civilian unit is created in this city. May not be built in an Encampment district that already has a Stable."
    },
    {
        name: "Palgum",
        icon: "../imgs/Palgum.webp",
        description: "Mesopotamia is a land with a complicated relationship with water. Between the dry desert and the flood-prone Tigris and Euphrates, the Babylonians had to learn how to control their rivers. And control them they did, even channeling the flow through palgum – small-scale canals – to feed elaborate gardens. While the Hanging Gardens of Babylon have not been as well documented as historians may have hoped, at Nineveh, the Assyrian king Sennacherib built a luxurious garden fed by aqueducts and elaborate canals – often the same waterway at different points, cutting through mountains and rising over canyons - that allowed for exotic trees such as ebony and rosewood to grow within the palace. These canals were reinforced by great limestone blocks and controlled by specialized sluice gates. The King was proud of these – he inscribed, “over deep-cut ravines, I spanned a bridge of white stone blocks. Those waters I caused to pass over upon it.” The Yazidi ethnic group in Iraq kept up this tradition of building elaborate aqueducts and canals well into the 20th century.",
        ability: "+2 Production +1 Housing +1 Food to all tiles adjacent to a source of fresh water."
    },
    {
        name: "Marae",
        icon: "../imgs/Marae.webp",
        description: "A marae is a meeting ground of the Maori, and the physical center of an iwi—a tribe or family. It is central to the identity and sense of self for the tribe and family, and the place where the family comes together to celebrate, mourn, welcome, and recommit themselves. Behavior on the marae is governed through important customs, which serve to reinforce the mana of the marae holder and their guests. A marae is not a permanent dwelling, but a place set aside where the family will go for important occasions. A marae will consist of a cleared space and buildings, including the distinctive meeting house (wharenui) with its large front portico (marae atea). The wharenui and marae atae have ornately carved pillars and panels that reflect the heritage of the people—their whakapapa. A guest is welcomed through a ritual called the powhiri, which begins with a challenge, moves onto recognition of the ancestry of both sides, includes formal speeches of welcome and exchange of gifts, and ends with a shared meal.",
        ability: "+1 Culture and Faith to all of this city's tiles with a passable feature. +1 Tourism to all of this city's tiles with a passable feature (with Flight). + Culture for each Cultural City-States with 3 Envoy (Turns into +1 Culture with each Cultural City-States with 1 Envoy). No maintenance cost. No Great Work slots."
    },
    {
        name: "Ordu",
        icon: "../imgs/Ordu.webp",
        description: "Simply translated, “ordu” means “palace tent.” However, an ordu was something much more than just a simple tent—it was the center of the tribe for the nomadic Mongolians. An ordu served as the headquarters and main encampment for the Khan and his warriors. Though built for travel, it had style, from simple decorations to carefully sewn patterns. The ordu moved with the Khan and his warriors as they went on campaign, ensuring they always felt at home no matter where they traveled.",
        ability: "+1 Production +1 Housing +1 Citizen slot +1 Great General point per turn +25% combat experience for all cavalry and siege units trained in this city +1 Movement for all cavalry units trained in this city +2 Production for units, for each Militaristic City-State with 3 Envoys (Turns into +1 Production for each Militaristic City-States with 1 Envoy). Strategic Resource stockpiles increased by 10"
    },
    {
        name: "Tlachtli",
        icon: "../imgs/Tlachtli.webp",
        description: "For over 2700 years the Mesoamericans played their traditional “ballgame” – Ollamaliztli in Nahuatl – in (not surprisingly) “ball courts.” Somewhat similar in play to team racquetball, these “sporting events” had significant ritual overtones, given that the losers (and sometimes the winners) were often sacrificed after the game, usually by decapitation. Explicit depictions of human sacrifice after a game can be found in many Mayan ball courts such as those at El Tajin and at Chichen Itza. Although the sport had somewhat different rules in different places and different times, it spread throughout Mesoamerica, as far south as Nicaragua and north as Arizona. Built in a pattern that changed little over two-and-a-half millennia, the ball courts were stone constructs of a long, narrow playing field between high sloped walls with open-ended (later enclosed) wider goal areas. Painted and decorated, these stadiums were the epitome of the Mesoamerican civilization … until the Spanish showed up and introduced the natives to other games.",
        ability: "+2 Faith +1 Great General point per turn Lower Production cost (135 vs. 150) +2 Amenity from Entertainment +1 Culture (2 Culture) +1 Tourism after developing the Conservation civic"
    },
    {
        name: "Sukiennice",
        icon: "../imgs/Sukiennice.webp",
        description: "Thanks to its location between Europe and Russia, Poland’s cities were vibrant with trade, as exemplified by the cloth halls (known as sukiennice in Polish) located in the great cities of the realm. It contained trading stalls, where vendors sold cloth, leather goods, wax, salt, peppers, spices, and silk from the Far East, indeed all sorts of exports and imports. Usually built in the center of towns, these were international marketplaces, larger and more magnificent than the run-of-the-mill markets scattered about Europe. In the halls and porticos, traders from dozens of lands made deals, and the locals—those who could afford it—found all the luxuries they could desire. In Poland, the oldest and largest was the Sukiennice of Krakow, rebuilt in the Renaissance style in 1555 AD after a fire. It was an important center for international trade between West and East until the end of the 16th Century (today its stalls sell snacks and souvenirs to tourists). But the cloth hall was also vital in other Polish cities, doing a booming trade in places such as Poznan, Wroclaw, and Torun.",
        ability: "+3 Gold (boosted by Free Market Policy Card) +1 Citizen slot +1 Great Merchant point per turn +4 Gold with each Trade City-States with 3 Envoy (Turns into +2 Gold with each Trade City-States with 3 Envoy in and +2 Gold with each Trade City-States with 1 Envoy). +4 Gold from domestic Trade Routes. +2 Production from international Trade Routes. +1 Trade Route capacity if this city doesn't have a Lighthouse."
    },
    {
        name: "Prasat",
        icon: "../imgs/Prasat.webp",
        description: "When not dominating the Mekong and the mainland of Southeast Asia, the kings of the Khmer empire would turn their attention to their faith. And what better way to venerate the gods than through erecting massive temples? These holy sites at the center of Khmer worship would serve as both symbols of their warrior-kings’ piety and their engineers' brilliance. The earliest Khmer temple on record is Prasat Ak Yom (c. 800), its design reflecting the South Indian tradition of 'ratha'-style temples, towering edifices terminating in a crown at the top. Of course, the Khmer would add their own flourish, adding prangs, or towers to the structures. The construction of these temples would become an enduring feature of subsequent Khmer rulers, first facing east in honor of the Hindu god Shiva, while later construction would turn west after Jayavarman VII introduced Mahayana Buddhism to the Empire in the Twelfth Century.",
        ability: "+6 Faith (boosted by Simultaneum Policy Card) +1 Citizen slot +1 Great Prophet point per turn +1 Relic slots +2 Faith with each Religious City-States with 6 Envoy (Turns into +2 Faith with each Religious City-States with 3 Envoy). Allows purchasing of Apostles, Gurus, Inquisitors (after an Apostle uses its Launch Inquisition ability), and Warrior Monks (with the proper belief) in this city +0.5 Culture for every Population in this city Provides 10 Tourism if the city has between 10 to 19 Population, and 20 Tourism instead if the city has 20 or more Population after Flight is researched."
    },
    {
        name: "Stave Church",
        icon: "../imgs/Stave_Church.webp",
        description: "After they got past their pagan ways, stave churches were wooden, post-and-beam constructions built throughout medieval Scandinavia once the Vikings converted to Christianity. In Sweden alone it is estimated that over a thousand stave churches were scattered about, the oldest dating back to the mid-1100s. Besides their religious function, these often served as meeting halls, cultural centers, courthouses, and even as marketplaces. Early stave churches were palisade constructions, with steeply pitched roofs to shed the heavy snows. The churches had elaborate wooden carvings, usually Christian in design but occasionally depicting pre-Christian heroes and myths. Later, only the corner posts were set in the earth, with planking covering the frame. Currently 30 stave churches remain standing, all but two in Norway.",
        ability: "Holy Site gets an additional standard adjacency bonus (+1) from Woods. +1 Production for every coastal resource worked by the city +4 Faith (boosted by Simultaneum Policy Card) +1 Citizen slot +1 Great Prophet point per turn +1 Relic slot +2 Faith with each Religious City-States with 6 Envoy (Turns into +2 Faith with each Religious City-States with 3 Envoy). Allows purchasing of Apostles, Gurus, Inquisitors (after an Apostle uses its Launch Inquisition ability), and Warrior Monks (with the proper belief) in this city."
    },
    {
        name: "Madrasa",
        icon: "../imgs/Madrasa.webp",
        description: "A madrasa (madrasah in Arabic or medrese in Turkish) is a secular institution of education, although often with a religious component. Madrasas would specialize in medicine, law, science, philosophy, religion or the education of women. Others also taught logic, world history, foreign languages, mathematics, art, and comparative literature. The first madrasa, the Gama'at al-Qarawiyyn, was established in 859 AD by Fatimah al-Fihri, the daughter of a wealthy merchant. During the rule of the Fatimid, Ayyubid, and Mamluk dynasties, the practice of sponsoring madrasas by the ruling, wealthy elite spread across Egypt and the Middle East. The first Ottoman madrasa was founded in 1331 in Iznik, and followed the traditions of Sunni Islam. The madrasas of the Turks and Arabs would, as Europe stumbled through the Dark Ages, keep the best of Classical knowledge alive, and build on it with their own inventions.",
        ability: "+5 Science (boosted by Rationalism Policy Card) Provides bonus Faith equal to the adjacency Science bonus of its district +1 Housing +1 Citizen slot +1 Great Scientist point per turn +2 Science for each Scientific City-States with 6 Envoy (Turns into +2 Science with each Scientific City-States with 3 Envoy)."
    },
    {
        name: "Navigation School",
        icon: "../imgs/Navigation_School.webp",
        description: "Sagres is the southernmost point in Portugal, the last safe shelter before ships would depart across the storm-tossed Atlantic. Looking south, Portuguese sailors faced rough seas and the forbidding “Cabo de Não” – “Cape No,” that stretch of the Atlantic coast of what is now Morocco where the Sahara begins. For long considered the end of the navigable world (hence the name) by European and Arab sailors, Cabo de Não (now called Cape Chaunar) had to be overcome for the Portuguese to realize their dream of a ship-based empire. The planning for – and ultimate success of – Portuguese expeditions around the Cape, and around other, farther, more forbidding capes, happened at schools of navigation. While some scholars interpret this “school” term loosely, noting that most Portuguese sailors probably did their studying practically aboard ships, others posit a centralized school of navigation – placed by the most romantically-inclined scholars right at the Sagres Point. From here, sailors would be able to see firsthand the dangers of the Atlantic… and plot out ways to overcome them.",
        ability: "+25% Production toward naval units in this city +1 Science for every two Coast or Lake tiles in this city +1 Great Admiral point per turn +4 Science (boosted by Rationalism policy card) +1 Housing +1 Citizen slot +1 Great Scientist point per turn +2 Science for each Scientific City-States with 6  Envoy (Turns into +2 Science with each Scientific City-States with 3 Envoy)."
    },
    {
        name: "Queen's Bibliotheque",
        icon: "../imgs/Navigation_School.webp",
        description: "'Bibliotheque' is the French word for a library, and as French was the vernacular language of culture from the Middle Ages through the Industrial Revolution, it is used here to reflect that history. The “Queen” in this case is in honor of Kristina of Sweden, who was a lavish patron of the arts and literature. Eleanor of Aquitaine was another notable patron of arts, especially the burgeoning troubadour tradition. Many other queens effectively used the soft power of her cultural patronage as tools of statecraft, sometimes gaining more than the king could on the battlefield.",
        ability: "+2 Great Writer points per turn. +2 Great Artist points per turn. +2 Great Musician points per turn. +2 Great Work of Writing slots. +2 Great Work of Art slots. +2 Great Work of Music slots. Awards +1 Governor Title."
    },
    {
        name: "Grand Bazaar",
        icon: "../imgs/Grand_Bazaar.webp",
        description: "The Ottoman Empire is well-known for their military conquests, but they were also a center for craft and trade. Since the Empire stood at the crossroads of Europe, Africa, and Asia, they stood to profit from the trade that passed through their borders. They controlled important trade cities like Istanbul, Cairo, and Baghdad. The Grand Bazaar of Istanbul is probably the oldest continually-operating bazaar in the world, and is one of the most popular tourist attractions on the planet. The word “bazaar” is Persian, and the oldest bazaars probably arose around caravansaries. A true bazaar takes place in a building, or under the cover of a permanent breezeway. A number of traditional bazaars are still found around the world, many of which still are vibrant, functioning markets, and some of which are UNESCO Heritage sites. Bazaars may be set up for the buying and selling of a single product, like grain or cloth, or they may be general markets where any number of things may be bought or sold. Bazaars were central to urban life of cities in the Ottoman Empire and surrounding lands. The rituals of buying and selling goods and information have worked their way into many languages and cultures in that part of the world.",
        ability: "+5 Gold (boosted by Free Market Policy Card) +1 Citizen slot +1 Great Merchant point per turn +2 Gold with each Trade City-States with 6 Envoy (Turns into +4 Gold with each Trade City-States with 3 Envoy). Lower Production cost (220 vs. 290) Accumulate one extra Strategic resource for every different type of Strategic resources this city has improved. Receive 1 Amenity for every type of Luxury resource this city has improved."
    },
    {
        name: "Tsikhe",
        icon: "../imgs/Tsikhe.webp",
        description: "High over the landscape, situated in the hills and rocky cliffs, the Georgian fortresses guard the countryside. The tsikhe feature high curtain walls with either rounded or triangular merlons (the solid part of the “cut outs” on the wall). A tower stands at each intersection of joined wall. The Georgian fortresses were particularly difficult to assault due to their position on the high ground. Although this type of fortress existed during the time of Alexander the Great, the Georgians used them effectively through the 17th Century.",
        ability: "Lower Production cost (260 vs. 300). +4 Faith. +200 Outer Defense Strength. +3 Combat Strength (Total of +9 Combat Strength from previous walls) +1 Housing under the Monarchy government. (Total of +3 Housing from previous walls) +2 Diplomatic Favor under the Monarchy government. Becomes obsolete with Steel, which automatically builds defenses in every city. Cannot be purchased with Gold. +3 Tourism (with Conservation. Total of +6 Tourism from previous walls. Total of +9 Tourism in a Golden Age)."
    },
    {
        name: "Electronics Factory",
        icon: "../imgs/Electronics_Factory.webp",
        description: "With the advent of consumer electronics, the market for all manner of gizmos and gadgets for entertainment, communication and wasting time exploded in the late 20th Century. The Consumer Electronics Association estimated that sales of electronics for personal use – from computers to MP3 players, calculators to digital cameras, and so forth – exceeded 150 billion dollars in 2007 AD. To feed this postmodern addiction, semi-skilled laborers working in sprawling electronics factories assemble standardized parts into an ever-increasing flood of new products. Leading the way in this tidal wave is Japan, with the largest electronics industry in the world, although both South Korea and China are increasingly competitive. The first “modern” electronics factory was built by Sony, founded in 1946 AD. In the 1950s, Japanese engineers pioneered commercial applications for the transistor and in the 1970s and 1980s for the semi-conductor. Japanese innovations in miniaturization and in standardizing electronics manufacturing have kept their factories the most profitable in the most competitive field in consumerism ever seen.",
        ability: "+3 Production to all City Centers within 6 tiles of the Electronics Factory's Industrial Zone +5 Production additionally when Power Powered Base Load: 2 Power +1 Citizen slot +1 Great Engineer point per turn +4 Culture (with Electricity)"
    },
    {
        name: "Thermal Bath",
        icon: "../imgs/Thermal_Bath.webp",
        description: "The culture of bathing in Hungary has deep roots from both the East and West, and the country is dotted with numerous natural thermal springs. Some of the most famous baths were built near Budapest, including the grand Szechenyi, the luxurious Art Nouveau styled Gellert, and the ancient Rudas (which still preserves much of its Ottoman style). The baths and their buildings boast grand architecture and artwork, and huge bathing pools. Hungary may have the largest proportion of thermal baths per capita of any country in the world, and they are a popular draw for tourists. If you go to a Hungarian thermal bath, you have a number of choices available to you. You can relax in the warm indoor pools and soak in the salubrious mineral waters. You may get a massage. You can visit a sauna, or douse yourself in cold water should you choose. You should definitely have a friendly chat with your companions. The quality of the water at each bath is said to benefit a specific set of conditions, which would seem to warrant an in-person comparison—for science's sake, of course.",
        ability: "+2 Amenities from entertainment to all City Centers within 6 tiles of the Thermal Bath's Entertainment Complex. +2 Production to all City Centers within 6 tiles of the Thermal Bath's Entertainment Complex. +3 Tourism and +2 additional Amenities to this city if there is at least one Geothermal Fissure within its borders."
    },
    {
        name: "Film Studio",
        icon: "../imgs/Film_Studio.webp",
        description: "The “Black Maria,” a tarpaper-covered shack in West Orange, New Jersey, built by Thomas Edison in 1893 AD, might generously be termed the first “movie studio”; there Edison used film to capture the antics of vaudeville and theater actors to show to the public in penny arcades, unused theaters, and fairground tents. In 1909, Edwin Thanhouser leased an old skating rink and made commercial films, some 1086 between 1910 and 1917. Meanwhile, in Europe, studios such as Pathé (France), Münchner Lichtspielkunst AG (Bavaria). Mosfilm (Russia) and Ealing Studios (UK) were being founded. But, for unexplained reasons, a number of studios sprouted up in and around Los Angeles (the best explanation being that natural sunlight was the best for the crude movie cameras of the time), the first being Nestor Studios in 1911. By 1920, there were a dozen in operation in the suburb of Hollywood cranking out film by the mile to feed civilization’s latest escapist addiction. Although film studios are largely passé (most production taking place “on location”), some remain in operation in odd corners of the globe.",
        ability: "+2 Culture (boosted by Grand Opera Policy Card) +4 Culture additionally when Power Powered Base Load: 3 Power +1 Citizen slot +1 Culture additionally per Specialist in this district +1 Great Artist point per turn +2 Great Musician points per turn +3 Culture for each Cultural City-States with 6 Envoy. +1 Great Work of Music slot +100% Tourism pressure from this city towards other civilizations starting from the Modern Era."
    },
    {
        name: "Observatory",
        icon: "../imgs/Campus.webp",
        description: "The Maya, who were both intensive agriculturalists as well as consummate mathematicians, took an intense interest in the movement of the heavens. At observatories in Mayan cities such as Palenque and Chichén Itzá, Mayan astronomers used an artificial horizon – a flat, circular platform of regular size – on which they marked carefully the points at which stars, planets, the moon and sun rose and fell each year. The Mayans used these observations to create detailed calendars. We are familiar with a solar one – our 365-day calendar is based upon the length of time that it takes for the sun to complete one cycle, but many cultures also use a lunar calendar (i.e. the length of time it takes for the moon to wax and wane 12 times). The Mayans added more and more cycles to this. For instance, the planet Venus takes 584 days to return to the same spot on the rim of one of the Mayan observatories’ artificial horizons. Noticing and recording this, the Maya also developed a Venusian calendar. Finally, to these astronomical observations, the Mayans added a 260-day calendar, one that lines up with the average time from human conception to birth. The function of this astronomy was astrology, religion, agriculture, and politics combined. The stars and planets (as were, at times, Mayan rulers) were Mayan gods. As calendars interlinked, different activities – planting, warfare, festivals, the fortunes of a particular leader – would become more or less auspicious. Astronomy via the observatory was, for the Mayans, a way of tracking how the natural world, the supernatural world, and the political world were interlinked. Today, astronomical observations and calendrical cycles still influence how present-day Maya practice indigenous religion and divination.",
        ability: "Lower Production cost (27 vs. 54). Major bonus (+2 Science) for every adjacent Plantation. Major bonus (+2 Science) for each adjacent Great Barrier Reef tile. Major bonus (+2 Science) for each adjacent Pamukkale tile. Minor bonus (+½ Science) for every adjacent Farm or district. +1 Great Scientist point per turn. Specialists add +2 Science each"
    },
    {
        name: "Seowon",
        icon: "../imgs/Campus.webp",
        description: "An educational crisis in 16th Century Korea brought about the seowon, a private institution designed to fill the scholarly void. The heavy emphasis on Confucian teachings and rituals were often expressed in the modest appearance of its structures. The preponderance of aristocratic children attending made the seowon ideal for discussing politics. This blend of Neo-Confucianism and topical matters created an ideal setting to explore new ideas about Korea’s contemporary culture and government.",
        ability: "Lower Production cost (27 vs. 54) Has a starting adjacency bonus of +4 Science -1 Science for each adjacent District +1 Great Scientist Point per turn Specialists add +2 Science each"
    },
    {
        name: "Acropolis",
        icon: "../imgs/Theater_Square.webp",
        description: "In ancient Greece, acropolis meant, quite literally, 'upper city.' And in Athens, Corinth, Argos, Thebes, and elsewhere, that's exactly what it was – a portion of the town built upon an elevated area, often a hill with steep slopes, that was eminently defensible. Should the outer walls fall to invaders, a final stand could be made in the acropolis. In time, in many places, the old acropolis became the nucleus of a sprawling new city. During the Archaic Period in Greece, as the cities grew and the threat of barbarians lessened, these old upper districts underwent urban renewal, with temples, theaters, forums, palaces, government buildings and the like replacing the humble houses, markets, barracks and squares that once occupied the summit.",
        ability: "Lower Production cost (27 vs. 54) Major bonus (+2 Culture) for each adjacent Wonder Standard bonus (+1 Culture) for each adjacent District, +1 additional Culture if adjacent to a City Center. Major bonus (+2 Culture) for each adjacent Entertainment Complex or Water Park Major bonus (+2 Culture) for each adjacent Pamukkale tile Awards 1 Envoy when completed +1 Great Writer point per turn +1 Great Artist point per turn +1 Great Musician point per turn Buildings have slots for Great Works and Artifacts Specialists add +2 Culture each"
    },
    {
        name: "Lavra",
        icon: "../imgs/Holy_Site.webp",
        description: "In the Eastern Orthodox tradition, a lavra (such as found at Mount Athos in Greece or Neamț in Romania) is a cloistered monastery of cells for hermits with a central church and/or rectory. Perhaps the most famous is the Alexander Nevsky Lavra (trust the Russians to name a holy place after a warrior) in St. Petersburg where many eminent but dead Russians are buried – besides Nevsky, there's Euler, Suvarov, Mussorgsky, Tchaikovsky, Dostoevsky and others. Believed to have its origins in the early 4th century AD, the first lavra seems to have been a settlement of some 600 hermits around Nitria in the Egyptian desert. In the strict Eremitic tradition, these hermit-monks lived a secluded life devoted to prayer, often accompanied by vows of silence, chastity, meditation and/or fasting. Further proof of the lengths to which some of the faithful will resort to be saved.",
        ability: "Lower Production cost (27 vs. 54) +2 Great Prophet points per turn +1 Great Writer point per turn if there is a Shrine in the Lavra +1 Great Artist point per turn if there is a Temple in the Lavra +1 Great Musician point per turn if there is a worship building in the Lavra Expands the city's borders whenever a Great Person Great Person is used in the city Major bonus (+2 Faith) for each adjacent Natural Wonder Standard bonus (+1 Faith) for each adjacent Mountain tile Standard bonus (+1 Faith) for each adjacent Pamukkale tile Minor bonus (+½ Faith) for each adjacent District tile and each adjacent Woods tile A religion can be founded in a Lavra Religious units can be purchased in a city with a Lavra, spawning in the Lavra or if that's unavailable in the City Center Religious units heal in a Lavra and in tiles adjacent to it Specialists add +2 Faith each"
    },
    {
        name: "Ikanda",
        icon: "../imgs/Encampment.webp",
        description: "The ikanda (also known as a “kraal” or “umuzi”) were self-sufficient, fortified Zulu homesteads. A double palisade protected its residents—the inner wall kept livestock in and the outer wall kept interlopers out. Ikanda were ideally placed uphill for reasons both practical and strategic: rainwater flowed downhill to clean the ikanda, while opponents were forced to attack an elevated position. Shaka’s revolutionary changes to the military capitalized on the traditional Zulu age-grade system. Young men of the same age lived, trained, and fought together in regiments, relying on the ikanda’s bounty to provide their food, arms, and armor.",
        ability: "Lower Production cost (27 vs. 54) +1 Housing 25% faster training of Corps and Armies Allows Corps and Armies to be built without the Military Academy building Buildings in the Ikanda provide +2 Gold and +1 Science +1 Great General point per turn Acquires Outer Defenses and Ranged Strike along with the City Center once Walls have been built Blocks movement of foreign units to this tile, unless the district is pillaged Spawns all land military units the city produces or purchases Provides XP bonus to units built in it once buildings have been added to the district Specialists provide +1 Production and 2 Gold each Spies operate at one level lower when targeting this city with Consulate Increases Strategic Resource stockpiles by 10 for each building inside"
    },
    {
        name: "Thành",
        icon: "../imgs/Encampment.webp",
        description: "The word “thành” refers to a citadel or fort, but classical Vietnamese architecture combined military protection with architectural artistry. The oldest thành in Vietnam is the Thành Cổ Loa, in a district of what is now Hà Nội. Local legend tells of how the king had angered a magical turtle by continually trying to build a thành on the turtle’s back. After becoming aware of this magical, talking, and very very angry turtle, the king agreed to relocate the site for the thành. In thanks, the turtle gave the king a magical crossbow, some thousand times the strength of an ordinary one. While the crossbow has been lost to time, the citadel still stands, with its spiral outer walls and rectangular internal keep. Thành often had a rectangular internal keep surrounded by a moat. The citadel’s walls could be thick and durable, but, at least in the case of the stunning thành at Huế, the upper level was often beautifully painted and carved with dragons and other auspicious symbols of royalty. In central Hà Nội, the thành Thăng Long remains the city’s predominant symbol, with its squat central tower and thick walls. Built in 1010, this central fortress was so impressive that it was used as a base by groups as disparate as the royal family, the French military during the colonial period, the Japanese imperial army (as a prison), and the communist People’s Army of Vietnam. It was not just a military outpost, though, as it was decorated with carved stone dragons, elaborate palaces (now destroyed), and, now, serves as a museum.",
        ability: "Lower Production cost (27 vs. 54) +2 Culture for every adjacent District Provides Tourism from Culture adjacency bonus after researching Flight Is not considered a specialty District and does not require Population Provides no Great General point Acquires Outer Defenses and Ranged Strike along with the City Center once Walls have been built Blocks movement of foreign units to this tile, unless the District is pillaged Spawns all land military units the city produces or purchases Provides XP bonus to units built in it once buildings have been added to the District When a Military Academy is built, parent city may also build units as Corps and Armies Specialists provide +1 Production and 2 Gold each Spies operate at one level lower when targeting this city with Consulate Increases Strategic Resource stockpiles by 10 for each building inside"
    },
    {
        name: "Suguba",
        icon: "../imgs/Commercial_Hub.webp",
        description: "In the Mande language, Suguba means 'big market,' and as the Malian empire was built on trade, one would naturally expect a bustling and vibrant market. Most of the cities of Mali have large market districts, crowded with vendors and customers. In the past, Malian gold and salt would have purchased a variety of goods from across Africa and Europe, which would have found their way into Malian markets. Should you visit a Malian Suguba, bring a shopping list and be prepared to negotiate your prices (bargaining is expected, and to fail to do so would be to commit a serious faux pas). In addition to more mundane goods like food and electronics, you should keep an eye out for Mali's famous fabrics: Bazin and bogolanfini. Bazin is a lustrous, colorful fabric made by the methodical hammering of cotton cloth, much prized by fashion designers around the world. Malians are said to be discriminating connoisseurs of bazin. Bogolanfini is a mud-dyed fabric of warm browns, deep blacks, and sharp whites, first worn by hunters, but now an important cultural symbol for Mali.",
        ability: "Lower Production cost (27 vs. 54). Major bonus (+2 Gold) for a nearby River or Holy Site. Major bonus (+2 Gold) for each adjacent Pamukkale tile. Minor bonus (+½ Gold) for each nearby District. 20% discount on all Gold Gold and Faith purchases in this city +1 Great Merchant point per turn Specialists add +4 Gold each"
    },
    {
        name: "Cothon",
        icon: "../imgs/Harbor.webp",
        description: "The word “cothon” is Greek for “drinking vessel,” and describes the circular shape of the artificial harbors created by the Phoenicians. There are surviving examples of these today in Sicily, Tunisia, and Cyprus. The best-known example may have been the one at Carthage. The cothon consisted of two sections: A long, rectangular outer harbor for merchant traffic, which led to a circular inner harbor for warships. The outer harbor's quays would have been busy places, and the cothon at Carthage was reputedly capable of supporting hundreds of ships at a time. Each night, the mouth of the harbor would have been secured with an iron chain for security. The inner, military harbor, was a protected and secure facility to build, repair, and outfit the Phoenician naval vessels for war. The inner harbor had an artificial island at the center for the commanding admiral. The outer ring of the military harbor would have contained slipways for ships, as well as naval stores and material for the repair and construction of new ships. The ancient writer Appian describes the Carthaginian military harbor as ringed by Ionic columns, “giving it the appearance of a continuous portico to both the harbor and the island.” The cothon was an integral part of the Phoenician dominance of the Mediterranean. Ships are expensive to build and maintain, and the construction of these specialized, sophisticated facilities demonstrate the Phoenician's commitment to ruling the seas.",
        ability: "Lower Production cost (27 vs. 54) +50% Production towards naval units and Settlers in this city All wounded naval units in the city's borders heal +100 HP each turn Major bonus (+2 Gold) for being adjacent to the City Center Standard bonus (+1 Gold) for each adjacent Sea resource Minor bonus (+½ Gold) for each adjacent District +1 Great Admiral point per turn Allows for sea lane Trade Route (even if the district is still under construction) Allows its parent city to build ships, even if the City Center is inland Newly produced or purchased ships will spawn at the Cothon tile (as long as the Cothon tile is unoccupied) Removes Movement penalties for units Embarking to and from its tile (even if the district is still under construction) When the Seaport is built, the parent city may construct Fleets and Armadas Buildings grant experience bonuses to ships built in this city Specialists add +2 Gold and +1 Food each"
    },
    {
        name: "Royal Navy Dockyard",
        icon: "../imgs/Harbor.webp",
        description: "Officially designated 'HM Royal Dockyards' until the late 1960s, the British Navy maintained a string of facilities around the world where its commissioned ships could be based, overhauled, refitted and repaired (if things afloat went wrong). The first, a shipbuilding yard as well as a dockyard, was designated such at Portsmouth in 1496 AD, just in time to bedevil the Spanish and French for the next couple centuries. The first outside the confines of Great Britain: the Royal Dockyard at English Harbor in Antigua in 1728. Through the Dutch Wars, Napoleonic Wars, colonial wars, and two world wars the Royal Dockyards did (not to mix metaphors overly) yeoman service. But with the reduced role of the Royal Navy and the erosion of the empire, in the latter part of the 20th century those Royal Dockyards that remain open have been largely converted to accommodation and training of naval personnel.",
        ability: "Lower Production cost (27 vs. 54) +1 Movement for all units built in Dockyard. +2 Gold when built on a foreign continent. +4 Loyalty when built on a foreign continent. Major bonus (+2 Gold) for being adjacent to the City Center. Standard bonus (+1 Gold) for each adjacent Sea resource. Minor bonus (+½ Gold) for each adjacent District. +2 Great Admiral points per turn. +1 Trade Route capacity if this city doesn't have a Commercial Hub. (Requires a Lighthouse) Allows its parent city to build ships, even if the City Center is inland. Newly produced or purchased ships will spawn at the Royal Navy Dockyard tile. Removes movement penalties for units Embarking to and from its tile. Allows its parent city to build Ships requiring strategic Resources with only 1 count of the relevant resource (prior to Gathering Storm). When the Seaport is built, the parent city may construct Fleets and Armadas. Buildings grant an experience bonus to ships built in this city. Specialists add +2 Gold and +1 Food each."
    },
    {
        name: "Hansa",
        icon: "../imgs/Industrial_Zone.webp",
        description: "From the Old French meaning “company of merchants,” the Hanse was a voluntary confederation of merchants and traders organized in a town for the protection and facility of commerce and transport. In the mercantile ports of the Baltic and North Sea these manufacturing and trading guilds became quite powerful and influential in the 13th Century, with their headquarters in complexes also known as the hansa. The largest hansa districts not only housed the administrative offices of competing guilds, but also storerooms, workshops, markets, banks and anything else that could turn a profit. The first such appears to have been built in Lubeck c. 1159 AD to facilitate trade between Western Europe and the resource-rich areas of northern Russia.",
        ability: "Lower Production cost (27 vs. 54). Major bonus (+2) to Production yield for each adjacent Commercial Hub. Major bonus (+2) to Production yield for each adjacent Aqueduct, Dam, or Canal. Standard bonus (+1) to Production yield for each adjacent resource. Minor bonus (+½) to Production yield for all other adjacent district tiles. +1 Great Engineer point per turn. Specialists provide +2 Production each Production from Factory and Power Plant buildings extends to cities whose City Centers are within 6 tiles of this district"
    },
    {
        name: "Oppidum",
        icon: "../imgs/Industrial_Zone.webp",
        description: "Oppidum simple means “settlement” in Latin, but in practice it referred to a walled urban settlement of a small town in Rome’s provinces – especially Gaul, and as such marks the first real cities in Europe north of the Alps. A classic oppidum was a combination of city and fort. Previously, citizens lived outside of protective walls, whereas armed soldiers or nobles had a hill fort: a high, fortified position. With an oppidum, economic and productive activity could occur in relative safety even with enemies nearly. The walls, too, made a separation between city-dwellers and rural residents, and allowed the former to feel a little sense of superiority over the latter, even if these “cities” were quite small by our – or even Roman – standards.",
        ability: "Lower Production cost (27 vs. 54) Acquires Outer Defenses and Ranged Strike along with the City Center once Walls have been built Unlocks Apprenticeship when the first Oppidum is built Major bonus (+2 Production) for each adjacent Quarry or Strategic Resource +1 Great Engineer point per turn Lowers the Appeal of nearby tiles Production from Factory and Power Plant buildings extends to cities whose City Centers are within 6 tiles of this district Specialists provide +2 Production each"
    },
    {
        name: "Street Carnival",
        icon: "../imgs/Entertainment_Complex.webp",
        description: "Many cities have street carnivals – especially during the Christian season of Lent – but only Brazilians really know how to cast care to the wind during such festivals. Parades, concerts, performances, masques, and public banquets (along with liberal amounts of alcohol) fuel the celebrations. According to stuffy postmodern sociologists, Carnival as a social institution provides more than just a respite from the seriousness of urban life, it serves as a release for natural impulses that threaten the social order and allows marginalized groups to focus attention on social conflicts by embodying them in 'senseless' activities. Whatever the truth of this interpretation, Rio de Janeiro's is the world's largest street carnival, hosting upwards of two million participants a day in recent years.",
        ability: "Lower Production cost (27 vs. 54). +2 Amenities from entertainment to parent city. Amenities from the Zoo and Stadium buildings extend to cities whose City Centers are up to 6 tiles away from the district."
    },
    {
        name: "Hippodrome",
        icon: "../imgs/Entertainment_Complex.webp",
        description: "The Byzantines, like the Romans before them, loved their chariot races. At the hippodrome (from the Greek “horse way”), teams of four-horse chariots would careen around the U-shaped track – a slight improvement to the bloody gladiatorial pits of Rome. Rivalries between teams were so intense that they put modern-day soccer or football rivalries to shame. In 532, the “Nika riots” between rival fans burned down half of the city of Constantinople and nearly killed the emperor Justinian. The hippodrome was vitally important, then, to the happiness (and, sometimes, unhappiness) of the city’s inhabitants, and was a site where citizens could see and cheer along with (or against) their Emperor.",
        ability: "Lower Production cost (27 vs. 54). +3 Amenities from entertainment to parent city Amenities from the Zoo and Stadium buildings extend to cities whose City Centers are up to 6 tiles away from the district. Provides a free heavy cavalry unit when first constructed and for each building constructed. These units require no resource to be created or maintain."
    },
    {
        name: "Copacabana",
        icon: "../imgs/Water_Park.webp",
        description: "Justifiably one of the most famous beach neighborhoods in the world (and interestingly, named for a place in the highlands of Bolivia) Copacabana looms large in Brazilian identity domestically and around the world. Officially nestled between Fort Copacabana at the south end and Fort Duque de Caxias at the north end, it was a luxurious neighborhood for the elite of Rio de Janeiro for most of its history, with the Copacabana Palace Hotel as its biggest landmark. In the 1970s when the narrow beach was expanded and the area became a booming destination for sunbathers and tourists of all social classes. It has served as a massive venue for concerts, New Year’s Eve celebrations, and even a papal Mass.",
        ability: "Lower Production cost (27 vs. 54) +2 Amenities from entertainment to parent city. Amenities from the Aquarium and Aquatics Center buildings extend to cities whose City Centers are up to 9 tiles away from the district."
    },
    {
        name: "Bath",
        icon: "../imgs/Aqueduct.webp",
        description: "In old Rome, the thermae were large bath complexes; while many Roman villas and palaces had private, heated baths, the thermae were public, open to all harried, dirty citizens who needed to relax and get clean. Although layout varied greatly from Roman city to Roman city, in general each had an atrium for relaxation and exercise, a caldarium (hot bath), a tepidarium (warm bath), a frigidarium (cool bath), as well as apodyterium (dressing room) and the like. The really nice ones also had a sudatorium (moist steam bath) and laconium (dry steam bath). The women's baths were almost as elaborate, and more highly decorated with murals and mosaics. After a long day at the Colosseum watching the slaughter, there must have been nothing as luxurious as a visit to the local thermae.",
        ability: "Lower Production cost (18 vs. 36). Provides the city with a source of fresh water from an adjacent River, Lake, Oasis, or Mountain. Cities that do not yet have existing fresh water receive up to 6 Housing Housing. Cities that already have existing fresh water will instead get +2 Housing Housing. Provides an additional bonus of +2 Housing and +1 Amenity in either case. Prevents Food loss during droughts. +1 Amenity if adjacent to a Geothermal Fissure. Does not depend on Population."
    },
    {
        name: "Mbanza",
        icon: "../imgs/Neighborhood.webp",
        description: "Mbanza is Kongolese for 'city,' or in some cases simply 'settlement.' By the time the Portuguese arrived in central Africa, M'banza Kongo was already a large city, rich from trade and craft manufacturing, but most of the population lived in the valleys that surrounded it in residential neighborhoods – perhaps as many as 100 thousand people. While these small towns might have a market and a workshop, the important things – churches, palace, schools, clinics, tax offices – were located in the hilltop capital. They were linked to M'banza Kongo by several roads up the slopes, and these were quite crowded at times such as feast and tax days. All this in 1648 AD according to the visitor Francesco da Roma. So not only did the Kongolese give civilization suburbia but also 'rush hour.'",
        ability: "Lower Production cost (27 vs. 54). +5 Housing +2 Food +4 Gold Yield does not change based on the tile's Appeal."
    },
    {
        name: "Château",
        icon: "../imgs/Chateau.webp",
        description: "If one must ask, one cannot afford it. A château is a manor house or country home of landed gentry, usually without fortifications. In the Middle Ages, a château was largely self-sufficient, being supported by the lord's demesne (hereditary lands). In the 1600s, the wealthy and aristocratic French lords dotted the countryside with elegant, luxuriant, architecturally refined mansions such as the Château de Maisons. But many of these stately homes were burned during peasant revolts and populist revolutions. But a few remain as tourist attractions. Today, the term château is loosely used; for instance, it is common for any winery or inn, no matter how humble, to prefix its name with 'Château.'",
        ability: "+2 Culture +1 Gold +1 Appeal +1 Culture for each adjacent wonder, increasing to +2 Culture per wonder (with Flight) +2 Gold if built on a River Provides Tourism equal to its Culture output (with Flight) Magnificence Catherine only: +2 Culture for improved Luxury resources adjacent to a Château or a Theater Square."
    },
    {
        name: "Chemamull",
        icon: "../imgs/Chemamull.webp",
        description: "The Mapuche erected great wooden tombstones to remember their dead. These chemamull are carved from a single log and placed beside a person’s tomb. These “people of wood” stand as tall as a person, crafted as recognizably male or female figures with arms crossed over their bodies. The Mapuche built these wooden statues to protect the spirits of their loved ones. They believed each statue guarded its tomb and helped to reunite a spirit with its ancestors.",
        ability: "+1 Production Provides Culture equal to 75% of its tile's Appeal."
    },
    {
        name: "Feitoria",
        icon: "../imgs/Feitoria.webp",
        description: "The feitoria – literally “factory” – was a trade depot set up overseas to facilitate trade, and, as such, it was a key institution of early mercantilist projects, especially the Portuguese networks of the early modern period (1300s-1600s). Here, European merchants could exchange goods in a space protected by European arms, operating with some degree of independence from the local ruler – and local pirates. Feitoria had a dark side, however: non-Europeans were not allowed to own land within one, and, later, they were key outposts of European colonization. Worse, the feitorias were key outposts in the trafficking of enslaved people. The first Portuguese feitoria was in the North African country of Mauritania, but later outposts were in Goa (in India), Malacca (in present-day Malaysia), Ternate (present-day Indonesia), Macau (in China), and Nagasaki (in Japan). In each spot, the Portuguese left their mark: Malacca and Goa have sizeable Catholic populations, Macau has impressive architecture left over from the Portuguese period, and bakers in Nagasaki still make Portuguese-style castella (kasutera, in Japanese) cakes.",
        ability: "+4 Gold +1 Production +4 Gold and +1 Production to Portuguese Trade Routes to this city"
    },
    {
        name: "Golf Course",
        icon: "../imgs/Golf_Course.webp",
        description: "There is one singular, undeniable historical constant: people have always enjoyed hitting balls with sticks. Scotland’s turf happened to be a perfect place to hit balls with sticks across large stretches of land. Thus “golf,” which means, “hitting a ball with a stick across a large stretch of land.” Golf courses became the stretches of land in question, frustrating generations of golfers with sand traps, lakes, the rough, and drops from highlands. Golf (as played today) managed to survive and thrive despite various attempts at banning the sport, by people such as King James II (who the Scots rightly ignored) and even the Scottish Church, who did not want it played during holy days. The Church’s larger complaint was with golfers playing in churchyards, which were a very particular sort of hazard.",
        ability: "+2 Amenities +2 Gold +1 Appeal +1 Culture if adjacent to a City Center +1 Culture if adjacent to an Entertainment Complex +1 Housing (with Globalization)"
    },
    {
        name: "Great Wall",
        icon: "../imgs/Great_Wall.webp",
        description: "A fortified border took on new meaning when some civilizations attempted to make sure the uncivilized stayed out. A number of empires built “great walls” – the Roman Hadrian’s Wall, the Chola-Pandya Madukkarai Wall, the Sassanid Great Wall of Gorgan, the French Maginot Line, and, of course, the Great Wall of China. Most were built of earth and stone, most incorporated natural terrain features (hills, rivers, and the like), and most had fortresses or garrisons scattered along their length. They were built in stages, sometimes over a long period of time. In terms of intent, none of these worked very well, for the outsiders managed time and again to “cross” the frontier walls, no matter how great. On the other hand, these great walls did provide a psychological sop to the empire’s citizens, and did deter the less barbaric barbarians from raiding the frontier settlements. With history having passed them by, most of the great walls have fallen into disrepair and obscurity … or become tourist traps.",
        ability: "Occupying unit receives +4 Defense Strength and automatically gains 2 turns of fortification (+6 Strength Defense Strength). +2 Gold +2 Gold for each adjacent Great Wall +2 Culture for each adjacent Great Wall (with Castles) Provides Tourism equal to its Culture output (with Flight) Can only be pillaged but never removed by disasters."
    },
    {
        name: "Hacienda",
        icon: "../imgs/Hacienda.webp",
        description: "Somewhere between a farm and a factory, the hacienda in Latin America was a large estate, held by a wealthy patron, that became the dominant mode of land ownership during the 19th century. Being located more inland than a plantation, and without the ready access to the sea, haciendas had to be agriculturally self-sufficient in addition to producing crops for export. In Gran Colombia, these crops could be coffee, coca, sugar, tobacco, or others. The hacienda system was by its very nature exploitative. While the enslavement of African-descended people was more dominant in coastal plantations, the inland haciendas relied upon the dispossession of indigenous peoples. These people often labored unpaid and, in exchange for their labor, “permitted” to remain on hacienda land – land that had been, in many cases, taken from them or from their ancestors in the first place. With the abolition of slavery, and with social and labor reforms in much of Latin America, the hacienda system has ended, although nostalgia-tinged farms or estates might still use the name.",
        ability: "+2 Gold +1 Production +0.5 Housing +1 Food from every two adjacent Plantations, increasing to +1 Food for each adjacent Plantation (with Replaceable Parts) Plantations and Haciendas receive +1 Production for every two adjacent Haciendas, increasing to +1 Production for each Hacienda (with Rapid Deployment)"
    },
    {
        name: "Ice Hockey Rink",
        icon: "../imgs/Ice_Hockey_Rink.webp",
        description: "There's nothing quite as satisfying as a game of ice hockey on a frozen pond on a sunny and cold winter day. Except sometimes the pond ice is uneven. Spectators can't always comfortably see what's going on. Bright and sunny winter days are subject to the vagaries of the weather. Organs are difficult to set up and take down between games. So there's really nothing quite as satisfying as a place that addresses some of those problems: The ice hockey rink. The skating craze at the end of the 19th Century led to a boom in rink construction. The first organized indoor hockey game was at the Victoria Skating Rink in Montreal in 1875. Since then, ice quality has improved due to improvements in ice formation chemistry and the domestication of the wild Zamboni. Amenities at the rink have improved as well to ensure fans have food and drink and boards to protect from errant pucks.",
        ability: "+1 Amenity +2 Appeal to surrounding tiles +1 Culture for each adjacent Tundra, Tundra Hills, Snow, and Snow Hills tile +2 Food and Production (with Professional Sports) +4 Culture if adjacent to a Stadium"
    },
    {
        name: "Kampung",
        icon: "../imgs/Kampung.webp",
        description: "In the densely-packed islands of Southeast Asia, local rulers faced the challenge of how best to house their people while also keeping them safe from floods and wildlife. Their answer – communities of tightly-clustered houses on stilts, or the kampung. While the term is a general one referring to a neighborhood, Indonesian kampungs were famous for helping Java achieve the highest population density of any island in the world. Indeed, foreign visitors were so impressed by the efficiency of Indonesian and Malay kampungs that they adopted the term in the English ‘compound.’",
        ability: "+1 Production +1 Housing +1 Food from every adjacent Fishing Boats Provides Tourism from Food Food after researching Flight +1 Housing (with Mass Production) +1 Production (with Civil Engineering)"
    },
    {
        name: "Kurgan",
        icon: "../imgs/Kurgan.webp",
        description: "For some reason, some of civilization’s greatest feats of engineering and construction are mausoleums and tombs, and, for some reason, these great piles are usually reserved for military and political leaders. For the Scythians these piles were great mounds of dirt, now called kurgans, from the Turkish word for “mound.” It appears that a number of the barbarian nomads of the steppes of Central Asia began interring their leaders in these mounds sometime around the 4th Century BC. By the Early Iron Age, the kurgans of the Scythians and other tribes were truly impressive mounds, some as much as 500 meters (1600 feet) across at the base, and might stand as high as 27 meters (89 feet). So, these tended to stand out on the rolling open terrain of the steppes. And then the Scythians decorated the tumuli with the bodies of slaves and horses, just to insure it got everyone’s attention that here lie a great man (or perhaps woman).",
        ability: "+1 Faith +3 Gold +1 Faith for each adjacent Pasture, increasing to +2 Faith for each adjacent Pasture (with Stirrups) Provides Tourism equal to its Faith output with Flight."
    },
    {
        name: "Mekewap",
        icon: "../imgs/Mekewap.webp",
        description: "Made from birch bark, the mekewap was a long-term shelter for the Cree intended to lodge many people. The Cree carefully laid out the wood into a dome shape, then wrapped wooden strips around the shelter. They then wove the strips together for warmth, further securing it from the elements. This careful construction prevented rain from permeating the shelter. The mekewap were not portable, but thankfully, they were relatively easy and quick to build.",
        ability: "+1 Production +1 Housing +1 additional Housing (with Civil Service). +1 additional Production (with Civil Service). +2 additional Gold for each adjacent Luxury Resource (with Cartography). +1 Food for every two adjacent Bonus Resources, increasing to +1 Food for each adjacent Bonus Resource (with Conservation)."
    },
    {
        name: "Mission",
        icon: "../imgs/Mission.webp",
        description: "According to the Catholic Church, missions are religious communities devoted to teaching, tending, and helping the local populace, thus supporting Christ’s ideals. Of course, the Spanish, Portuguese and French missions were also devoted to converting the locals and then “civilizing” them through cultural assimilation. The Spanish missions serve as the traditional template, self-supporting enclaves with churches, dormitories, fields and pastures, gardens, barns, workrooms, hospitals and schools. In places these were even fortified, ready to defend themselves from opposition. Most of the missions in the Americas, Asia, and Africa were administered by religious orders such as the Franciscans, Jesuits, Dominicans, and Augustinians rather than the Church itself, but the effects were the same. Nonetheless, the missions often served as a nucleus around which European colonizing efforts could coalesce.",
        ability: "+2 Faith +2 Faith additionally, 1 Food, 1 Production if on a different continent than your Capital +1 Science for every adjacent Campus and Holy Site +2 Science (requires Cultural Heritage) +2 Loyalty per turn for cities with a Mission next to the City Center and not on the original Capital's continent"
    },
    {
        name: "Nubian Pyramid",
        icon: "../imgs/Nubian_Pyramid.webp",
        description: "During their on-again/off-again periods of mutual conflict, Nubia found its culture influenced by the powerful Egyptian dynasties further down the Nile. Nubian burial customs would eventually come to resemble those of Egypt. Nubia’s Kingdom of Kush began burying its kings and queens in pyramids sometime in the First Millennium BCE. Nubia took a vastly different approach to its pyramids than Egypt. Rather than build immense tomb complexes that bankrupted their state, they opted for a more practical method: smaller pyramids with no more than a 26 ft (8 m) wide base, steep sides that rose at a sharp angle in the air, and an ornate entry chamber that extended from the pyramid tomb. Though treasure hunters plundered most of these pyramids since Nubia's fall, the pyramids remain a powerful testament to Nubia's legacy.",
        ability: "+2 Faith +2 Food +1 Food if adjacent to a City Center +1 Science for each adjacent Campus +1 Gold for each adjacent Commercial Hub or Harbor +1 Faith for each adjacent Holy Site +1 Production for each adjacent Industrial Zone +1 Culture for each adjacent Theater Square"
    },
    {
        name: "Open-Air Museum",
        icon: "../imgs/Open-Air_Museum.webp",
        description: "There are a lot of things which are worth preserving and studying for future generations, but not all of them fit nicely into glass cases or hang well on the walls. You might want to preserve something as complex as a village or a farm to show how it would have worked as a system, or to show a way of life no longer widely practiced. It was in this spirit that the open air museum was created. The first open air museum was King Oscar II's collection outside of Oslo, Norway, which includes a traditional Norwegian Stave Church (see the Stave Church entry for more information). The Skansen in Stockholm, Sweden, was founded in 1891 to preserve the declining traditions of Swedish rural life in the face of growing urbanization and industrialization. The term “skansen” has entered the lexicon as a shorthand for open air museums, especially those that focus on collecting historical structures. Open air museums celebrate culture beyond that typically preserved in museums—honoring the culture of ordinary people, not merely the great and grand. A folk song or blacksmith's craft taught to a future generation surely serves to link a people to their past as surely as an operatic aria or an allegorical oil painting. Perhaps even more so.",
        ability: "+2 Loyalty per turn in this city. +2 Culture and +2 Tourism for each type of terrain (Snow, Tundra, Desert, Plains, or Grassland) in which at least one Swedish city is founded."
    },
    {
        name: "Outback Station",
        icon: "../imgs/Outback_Station.webp",
        description: "Outback stations are known for their broad expanses of land, livestock herds, and self-sufficiency. Somewhat analogous to a ranch, the distinctly Australian stations are run by graziers in remote and somewhat inhospitable areas. They are often immense to compensate for thinly productive grazing ground and the occasional drought. Predictably, cattle stations stock cattle and sheep stations stock sheep. Wild dingoes find sheep to be delicious and defenseless, so graziers in dingo-infested areas traditionally shifted their stock to the (mostly) dingo-proof cattle.",
        ability: "+1 Food +1 Production +0.5 Housing +1 Food from every adjacent Pasture +1 Production to every adjacent Pasture (with Steam Power) +1 Production from every 2 adjacent Outback Stations (with Steam Power) +1 Food from every 2 adjacent Outback Stations (with Rapid Deployment)"
    },
    {
        name: "Pā",
        icon: "../imgs/Pa.webp",
        description: "The Maori constructed sophisticated hilltop fortifications, called Pā. These consisted of clearing and terracing a hilltop, erecting a palisade wall (or series of palisades), and constructing earthworks, foot storage pits, and water sources. Some Pā were large enough to support limited agriculture at their heart. A Pā conveyed a great deal of mana on the iwi which constructed it, in much the way a castle conveyed power to the nobility of feudal cultures. During the Maori wars with the British, the Pā of the North Island were centers of strong resistance for the Maori. In response to the introduction of gunpowder weapons, the Maori quickly modified their Pā design to include interlocking fields of fire for the defenders, and soft flax padding on the palisades that would dissipate the damage from bullets and shells. Only with heavy artillery could the colonial troops crack a Pā. Pā represent ingenious use of local resources to build strong defenses. The Maori quickly adapted the design of the Pā as new European weapons were introduced to the island, rapidly recapitulating the history of European fortification development in only a few generations on their own. There are many old Pā sites still visible around New Zealand today.",
        ability: "Occupying unit receives +4 Strength Defense Strength and automatically gains 2 turns of fortification (+6 Strength Defense Strength). A Māori unit occupying a Pā heals even if it just moved or attacked."
    },
    {
        name: "Pairidaeza",
        icon: "../imgs/Pairidaeza.webp",
        description: "A pairidaeza is a specific style of garden consisting of cultivated land within an enclosure. Also known as a “paradise garden,” the pairidaeza is thought to originate in the time of the Assyrian Empire. Its rectangular construction serves to contrast the external wildness of nature with an ordered and beautiful garden. Water was often an important element of their construction—ponds, canals, or even fountains flowed freely within the walls. As a tool of state, they were invaluable in flaunting a kingdom’s ability to bring life to an area that would otherwise have none. The Achaemenid dynasty melded the pairidaeza with their royal hunting parks, a not so subtle way to show their command over both their empire and the natural world within it.",
        ability: "+1 Culture +2 Gold +1 Appeal +1 Culture for every adjacent Holy Site and Theater Square +1 Gold for every adjacent Commercial Hub and City Center +1 Culture (with Diplomatic Service)"
    },
    {
        name: "Polder",
        icon: "../imgs/Polder.webp",
        description: "Most see the shoreline as an end. For the Dutch, the coastline was a challenge and an opportunity. The Netherlands spent 800 years reclaiming a country from the sea, using dikes, canals, levees, and pumps. Polders are the low-lying bits of land revealed when the water recedes. The Dutch constantly maintained their polders to prevent the sea from reclaiming the land. Over the centuries, they mastered the art of keeping water out and reversing the effects of erosion. Today, more than a quarter of the Netherlands remains below sea level, leaving the country in a continuous game of tug-of-war with the North Sea.",
        ability: "+1 Food +1 Food for every adjacent Polder, increasing to +2 Food for each adjacent Polder (with Replaceable Parts) +1 Production +0.5 Housing +4 Gold (with Civil Engineering) +1 Production for every adjacent Polder (with Replaceable Parts) Increases Movement cost of tile to 3."
    },
    {
        name: "Qhapaq Ñan",
        icon: "../imgs/Qhapaq_Nan.webp",
        description: "The Qhapac Ñan, also known as the Andean Road System, is a network of roads used by the Incan empire. What makes this site so remarkable isn't simply the distance covered – over 30,000 km – but also the terrain through which the roads travel - the mountains of the Andes, deserts, and lush rainforests. While the roads were used for transporting goods – usually by llama or alpaca – there was also in place a speedy messenger system. The chasquis were quick and agile men who would run through the extensive network of roads to pass messages to one another at relay stations until the message reached its final destination. The Andean Road System was a truly innovative means for keeping such a vast empire connected, and to some extent, controlled by a central power.",
        ability: "Allows units to move into it and exit through another Qhapaq Ñan at the cost of 2 Movement."
    },
    {
        name: "Rock-Hewn Church",
        icon: "../imgs/Rock-Hewn_Church.webp",
        description: "In the 11th century, Ethiopian Christians found themselves cut off. Whereas in centuries before, pilgrims from the ancient Christian centers would travel to the Holy Land, but Muslim conquests prevented these travels. King Lalibela, then, decided to construct a site closer to home, something impressive enough to draw pilgrims from the region without them having to travel across a war-torn region. To this end, he ordered the construction of a “New Jerusalem” – the rock-hewn churches of Lalibela. These were not ordinary churches. Instead, each was carved from a single giant stone, including doors, windows, columns, along with all of the practicalities: drainage ditches, catacombs, and hermits’ caves. As was required by the order to create a “New Jerusalem,” these churches include replicas of Jesus’s birthplace and tomb, so that visiting pilgrims could feel that they were able to commune with God without risking life and limb. They were – and remain - vital places of pilgrimage and worship for Coptic Christians.",
        ability: "+1 Faith +1 Faith for every adjacent Mountain and Hills tile Provides Tourism from Faith after researching Flight +1 Appeal. Can never be destroyed (only pillaged) by natural disasters"
    },
    {
        name: "Sphinx",
        icon: "../imgs/Sphinx.webp",
        description: "In contrast to the Greek version, the Egyptian sphinx has a human head on a lion’s body, is benevolent, and is the guardian of temples and tombs. Perhaps the first Egyptian sphinx constructed was during the Fourth Dynasty (c. 2500 BC) that depicted the face of Queen Hetepheres II, daughter of famed Khufu. But the sphinx was a common motif among those eternity-obsessed pharaohs; other famous ones include that depicting Hatshepsut and the “alabaster sphinx” of Memphis. Then there is that “Great Sphinx” at Giza that bears the likeness of the pharaoh Khafra (who is otherwise historically insignificant). Smaller ones lined the approaches to tombs and temples, and any number were put at the top of stairways in palaces and public places. By the 18th Dynasty, one could hardly swing a cat in Egypt without hitting a sphinx.",
        ability: "+1 Culture +1 additional Culture if built on Floodplains +1 additional Culture (with Natural History) +2 Appeal +1 Faith +2 additional Faith if placed next to a Wonder"
    },
    {
        name: "Stepwell",
        icon: "../imgs/Stepwell.webp",
        description: "A “stepwell” is a well or pool that can be reached by a set of steps. Although found in other regions, stepwells (known by a variety of names) are prevalent in India and Southeast Asia. The first rock-cut stepwells in India date from around 200 BC, and by 600 AD they were common throughout the Gujarat region; scholars believe that “cylindrical brick-lined wells” were a product of the early Bronze Age Indus Valley civilization. Many of the ancient Indian settlements had stepwells, and the elaborate ornamentation – some as detailed as those of any Hindu temple – show they were highly thought of by the citizenry. Not surprising, given the scarcity of clean water in the area. Alas, the British overseers of the Raj found the hygiene of the wells less than desirable, and so installed pumps and pipes to replace the stepwells in their holdings. Far less picturesque, but certainly more efficient.",
        ability: "+1 Housing +1 Food +1 additional Food if placed adjacent to a Farm +1 additional Faith if placed adjacent to a Holy Site +1 Faith (with Feudalism). +1 Housing (with Sanitation). +1 Food (with Professional Sports). Prevents Food Food loss from droughts."
    },
    {
        name: "Terrace Farm",
        icon: "../imgs/Terrace_Farm.webp",
        description: "The Incan terrace farm is one of the most sophisticated engineering works and agricultural systems developed in South America, and one whose complexities and benefits have only recently come into fuller appreciation. The Inca created arable land in a dry mountain region, capable of supporting a variety of crops and animals, and linked together to make optimal use of scarce resources and microclimate variations. Terrace farms have extensive irrigation canals and cisterns to move water to needed locations. The terraces provide level ground to grow crops, and the stone walls help preserve the day's heat and transfer it back to the soil at night, which mitigates crop freezing. Higher elevations were used as pastoral land for the llamas and alpacas, and different crops planted at different elevations, with the hardier crops like potatoes being raised higher. Each terrace was well-drained, and the water would flow down to help irrigate the terrace below. Lower terraces could be used to raise beans, peppers, and various gourds. The system of terrace farming produced enough surplus food that the Incas created and maintained caches of food for times of drought or disaster. In recent years, archaeologists and indigenous Andean communities have begun work to understand the terrace farms in the context of this agricultural system. They are rehabilitating some terraces and reintroducing some of the terrace farming techniques their Incan ancestors pioneered in order to feed a growing South American population.",
        ability: "+1 Food +1 Housing +1 Food for each adjacent Mountain +2 Production for each adjacent Aqueduct +1 Production if adjacent to Fresh Water and not an Aqueduct"
    },
    {
        name: "Ziggurat",
        icon: "../imgs/Ziggurat.webp",
        description: "When the Egyptians were building pyramids along the Nile, the Akkadians, Sumerians, Elamites, Babylonians and Assyrians were building ziggurats all over Mesopotamia. These were terraced pyramids, sometimes truncated so a temple could be placed on top. The earliest date from the Early Dynastic Period, roughly 2900 to 2400 BC, and the newest found date to c. 600 BC. Sun-baked bricks made up the center, and were faced with fire-glazed bricks that were more durable. Unlike the Egyptian pyramids, the ziggurats were generally solid, with shrines and temples on the summit, occasionally more than one (since one didn’t want to offend any god). Sadly none of the shrines or temples have survived – thanks to war, earthquakes and religious fervor – although the great piles of brick have. There were a number of “great” ziggurats, including the one in Babylon dedicated to the god Marduk which may have inspired the fable of the Tower of Babel.",
        ability: "+2 Science +1 Culture if placed adjacent to a River +1 Culture (with Natural History)"
    }
]

const seedBuildings = () => Building.bulkCreate(buildingData)

module.exports = seedBuildings