const { Civ } = require('../models')

const civData = [
    {
        name: "America",
        icon: "../imgs/American.webp",
        ability_name: "Founding Fathers",
        ability: "Government legacy bonuses accumulate in half the usual number of turns. All Diplomatic policy slots in the current government are converted to Wildcard slots. +1 Diplomatic Favor per turn for each Wildcard slot in the current government.",
        unitId: 53,
        unitId: 57,
        buildingId: 16,
    },
    {
        name: "Arabia",
        icon: "../imgs/Arabian.webp",
        ability_name: "The Last Prophet",
        ability: "Automatically receives the final Great Prophet when the next-to-last one is claimed (unless one has already been earned through other means). +1 Science per foreign city following Arabia's Religion.",
        unitId: 30,
        buildingId: 9,
    },
    {
        name: "Australia",
        icon: "../imgs/Australian.webp",
        ability_name: "Land Down Under",
        ability: "+3 Housing in coastal cities. Building a Pasture triggers a Culture Bomb, claiming surrounding tiles. Campus, Commercial Hub, Holy Site, and Theater Square districts gain +1 to their yields in tiles with Charming Appeal, and +3 with Breathtaking Appeal.",
        unitId: 54,
        buildingId: 46,
    },
    {
        name: "Aztec",
        icon: "../imgs/Aztec.webp",
        ability_name: "Legend of the Five Suns",
        ability: "Can spend Builder charges to complete 20% of a district's Production cost.",
        unitId: 2,
        buildingId: 5,
    },
    {
        name: "Babylon",
        icon: "../imgs/Babylonian.webp",
        ability_name: "Enuma Anu Enlil",
        ability: "Eurekas instantly unlock their respective technologies. -50% Science per turn.",
        unitId: 9,
        buildingId: 2,
    },
    {
        name: "Brazil",
        icon: "../imgs/Brazilian.webp",
        ability_name: "Amazon",
        ability: "Rainforest tiles provide a +1 adjacency bonus for Campus, Commercial Hub, Holy Site, and Theater Square districts, and grant +1 Appeal to adjacent tiles, instead of the usual -1.",
        unitId: 51,
        buildingId: 28,
        //buildingId: 30,
    },
    {
        name: "Byzantium",
        icon: "../imgs/Byzantine.webp",
        ability_name: "Taxis",
        ability: "+3 Combat and Religious Strength for all units for each Holy City converted to Byzantium's Religion (including Byzantium's own Holy City). Byzantium's Religion is spread to nearby cities when a unit from an enemy civilization or city-state is defeated. +1 Great Prophet point from Holy Sites.",
        unitId: 12,
        unitId: 34,
        buildingId: 29,
    },
    {
        name: "Canada",
        icon: "../imgs/Canadian.webp",
        ability_name: "Four Faces of Peace",
        ability: "Cannot declare Surprise Wars or war on city-states. Surprise Wars cannot be declared on Canada. For every 100 Tourism earned, gain 1 Diplomatic Favor. +100% Diplomatic Favor gained from succesfully completing Emergencies and Competitions.",
        unitId: 55,
        buildingId: 39,
    },
    {
        name: "China",
        icon: "../imgs/Chinese.webp",
        ability_name: "Dynastic Cycle",
        ability: "Eurekas and Inspirations provide an extra 10% of the Science and Culture cost for researching technologies and civics. Completing a Wonder grants a Eureka and Inspiration from that Wonder's era.",
        unitId: 24,
        buildingId: 37,
    },
    {
        name: "Cree",
        icon: "../imgs/Cree.webp",
        ability_name: "Nîhithaw",
        ability: "Gains +1 Trade Route capacity and a free Trader with Pottery. Unclaimed tiles within three tiles of a Cree city come under Cree control when a Trader first moves into them.",
        unitId: 7,
        buildingId: 42,
    },
    {
        name: "Netherlands",
        icon: "../imgs/Dutch.webp",
        ability_name: "Grote Rivieren",
        ability: "Rivers provide a +2 adjacency bonus for Campus, Theater Square, and Industrial Zone districts. Building a Harbor triggers a Culture Bomb, claiming surrounding tiles. +50% Production Production towards the Dam district and Flood Barrier building.",
        unitId: 39,
        buildingId: 49,
    },
    {
        name: "Egypt",
        icon: "../imgs/Egyptian.webp",
        ability_name: "Iteru",
        ability: "+15% Production towards Districts and wonders built next to a river. Districts, improvements and units are immune to damage from floods.",
        unitId: 6,
        buildingId: 52,
    },
    {
        name: "England",
        icon: "../imgs/English.webp",
        ability_name: "Workshop of the World",
        ability: "Iron and Coal Mines accumulate +2 resources per turn. +100% Production towards Military Engineers. Military Engineers receive +2 charges. Buildings that provide additional yields when powered receive +4 of their respective yields. +20% Production towards Industrial Zone buildings. Harbor buildings grant +10 Strategic Resource stockpiles.",
        unitId: 44,
        unitId: 52,
        buildingId: 25,
    },
    {
        name: "Ethiopia",
        icon: "../imgs/Ethiopian.webp",
        ability_name: "Aksumite Legacy",
        ability: "Improved resource tiles receive +1 Faith for each copy of that resource the city owns. International Trade Routes grant +0.5 Faith for each resource in the origin city. Can purchase Archaeologists and Archaeological Museums with Faith.",
        unitId: 32,
        buildingId: 51,
    },
    {
        name: "France",
        icon: "../imgs/French.webp",
        ability_name: "Grand Tour",
        ability: "+20% Production towards Medieval, Renaissance and Industrial Era Wonders. Double Tourism from Wonders of any Era.",
        unitId: 47,
        buildingId: 33,
    },
    {
        name: "Gaul",
        icon: "../imgs/Gallic.webp",
        ability_name: "Hallstatt Culture",
        ability: "Mines gain +1 Culture, grant a +0.5 adjacency bonus for districts and trigger a Culture Bomb when built, claiming surrounding unowned tiles. Specialty districts do not receive adjacency bonuses from other districts and cannot be built next to the City Center.",
        unitId: 3,
        buildingId: 27,
    },
    {
        name: "Georgia",
        icon: "../imgs/Georgian.webp",
        ability_name: "Strength in Unity",
        ability: "Dedications chosen at the beginning of a Golden Age or Heroic Age also grant their Normal Age bonuses towards improving Era Score, in addition to their regular bonuses. +50% Production towards walls.",
        unitId: 29,
        buildingId: 13,
    },
    {
        name: "Germany",
        icon: "../imgs/German.webp",
        ability_name: "Free Imperial Cities",
        ability: "Each city can build one more specialty District than the Population limit would normally allow.",
        unitId: 56,
        buildingId: 26,
    },
    {
        name: "Gran Colombia",
        icon: "../imgs/Gran_Colombian.webp",
        ability_name: "Ejército Patriota",
        ability: "+1 Movement for all units. Promoting a unit does not end that unit's turn.",
        unitId: 50,
        buildingId: 38,
    },
    {
        name: "Greece",
        icon: "../imgs/Greek.webp",
        ability_name: "Plato's Republic",
        ability: "Gains an additional Wildcard policy slot in all Governments.",
        unitId: 4,
        buildingId: 19,
    },
    {
        name: "Hungary",
        icon: "../imgs/Hungarian.webp",
        ability_name: "Pearl of the Danube",
        ability: "+50% Production for districts and buildings built across a river from a City Center.",
        unitId: 23,
        //unitId: 49,
        buildingId: 15,
    },
    {
        name: "Inca",
        icon: "../imgs/Incan.webp",
        ability_name: "Mit'a",
        ability: "Citizens can work Mountain tiles. Mountain tiles provide +2 Production, increasing to +3 Production after reaching the Industrial Era, and +1 Food for each adjacent Terrace Farm.",
        unitId: 36,
        buildingId: 50,
        buildingId: 54,
    },
    {
        name: "India",
        icon: "../imgs/Indian.webp",
        ability_name: "Dharma",
        ability: "Indian cities receive the Follower Beliefs of all religions with at least one follower in them, not just the majority religion, and gain +1 Amenity for each religion with at least one follower in them. +2 Spread Religion charges for Missionaries. +100% Religious pressure from Indian Trade Routes.",
        unitId: 20,
        buildingId: 53,
    },
    {
        name: "Indonesia",
        icon: "../imgs/Indonesian.webp",
        ability_name: "Great Nusantara",
        ability: "Coast and Lake tiles provide a +0.5 adjacency bonus for Holy Site, Campus, Industrial Zone, and Theater Square districts. Entertainment Complexes built adjacent to a Coast or Lake tile provide +1 Amenity.",
        unitId: 27,
        buildingId: 40,
    },
    {
        name: "Japan",
        icon: "../imgs/Japanese.webp",
        ability_name: "Meiji Restoration",
        ability: "Districts receive a +1 adjacency bonus for each adjacent district, instead of +0.5.",
        unitId: 33,
        buildingId: 14,
    },
    {
        name: "Khmer",
        icon: "../imgs/Khmer.webp",
        ability_name: "Grand Barays",
        ability: "Cities with an Aqueduct receive +1 Amenity, and +1 Faith for every Population. Farms receive +2 Food when adjacent to an Aqueduct, and +1 Faith when adjacent to a Holy Site.",
        unitId: 25,
        buildingId: 7,
    },
    {
        name: "Kongo",
        icon: "../imgs/Kongolese.webp",
        ability_name: "Nkisi",
        ability: "Relics, Artifacts and Sculptures grant +2 Food, +2 Production, +1 Faith, and +4 Gold. The Palace has four extra slots for Great Works. +50% Great Artist, Great Musician, and Great Merchant points gained from all sources.",
        unitId: 17,
        buildingId: 32,
    },
    {
        name: "Korea",
        icon: "../imgs/Korean.webp",
        ability_name: "Three Kingdoms",
        ability: "Farms receive +1 Food and Mines receive +1 Science for each adjacent Seowon.",
        unitId: 40,
        buildingId: 18,
    },
    {
        name: "Macedon",
        icon: "../imgs/Macedonian.webp",
        ability_name: "Hellenistic Fusion",
        ability: "Conquering a city grants a free Eureka for each Encampment and Campus district in the conquered city and a free Inspiration for each Holy Site and Theater Square district.",
        unitId: 14,
        buildingId: 1,
    },
    {
        name: "Mali",
        icon: "../imgs/Malian.webp",
        ability_name: "Songs of the Jeli",
        ability: "City Centers gain +1 Faith and +1 Food for every adjacent Desert and Desert Hills tile. Mines receive -1 Production and +4 Gold. May purchase Commercial Hub buildings with Faith. -30% Production towards buildings and units.",
        unitId: 31,
        buildingId: 23,
    },
    {
        name: "Māori",
        icon: "../imgs/Maori.webp",
        ability_name: "Mana",
        ability: "Starts with Sailing and Shipbuilding unlocked and the ability to enter Ocean tiles. +5 Combat Strength and +2 Movement for embarked units. Unimproved Woods and Rainforests grant +1 Production, increasing to +2 Production with Mercantilism and +3 Production with Conservation. +1 Food from Fishing Boats. Building a Fishing Boat triggers a Culture Bomb, claiming surrounding tiles. Resources cannot be harvested. Great Writers cannot be earned.",
        unitId: 19,
        buildingId: 3,
        //buildingId: 47,
    },
    {
        name: "Mapuche",
        icon: "../imgs/Mapuche.webp",
        ability_name: "Toqui",
        ability: "Cities with an established Governor gain +5% Culture, +5% Production, and +10% combat experience towards all units trained in the city. These numbers are tripled in cities not founded by the Mapuche. All cities within 9 tiles of a city with your Governor gain +4 Loyalty per turn towards your civilization.",
        unitId: 42,
        buildingId: 34,
    },
    {
        name: "Maya",
        icon: "../imgs/Mayan.webp",
        ability_name: "Mayab",
        ability: "Cities do not receive additional Housing from being adjacent to fresh water or coast. Cities gain +1 Amenity for each Luxury Resource adjacent to the City Center. Farms grant +1 Housing, +1 Production if adjacent to an Observatory, and +1 Gold.",
        unitId: 5,
        buildingId: 17,
    },
    {
        name: "Mongolia",
        icon: "../imgs/Mongolian.webp",
        ability_name: "Örtöö",
        ability: "Sending a Trade Route immediately creates a Trading Post in the destination city, instead of when the Trade Route is completed. Gains an extra level of Diplomatic Visibility with civilizations that have a Mongolian Trading Post. +6 Combat Strength for all units for each level of Diplomatic Visibility Mongolia has over the other civilization, instead of the usual +3 Combat Strength.",
        unitId: 28,
        buildingId: 4,
    },
    {
        name: "Norway",
        icon: "../imgs/Norwegian.webp",
        ability_name: "Knarr",
        ability: "Can enter Ocean tiles with Shipbuilding, instead of Cartography. All units pay no Movement cost to embark or disembark. Naval melee units can heal in neutral territory.",
        unitId: 10,
        unitId: 22,
        buildingId: 8,
    },
    {
        name: "Nubia",
        icon: "../imgs/Nubian.webp",
        ability_name: "Ta-Seti",
        ability: "+30% Production toward Ranged units. Ranged units gain +50% combat experience. +1 Production for Mines over strategic resources, and +2 Gold for Mines over bonus and luxury resources.",
        unitId: 8,
        buildingId: 44,
    },
    {
        name: "Ottoman",
        icon: "../imgs/Ottoman.webp",
        ability_name: "Great Turkish Bombard",
        ability: "+50% Production toward Siege units. Siege units gain +5 Combat Strength against defensible Districts. Conquering a city doesn't cause that city to lose Population. +1 Amenity and +4 Loyalty per turn for cities not founded by the Ottomans.",
        unitId: 21,
        unitId: 41,
        buildingId: 12,
    },
    {
        name: "Persia",
        icon: "../imgs/Persian.webp",
        ability_name: "Satrapies",
        ability: "Gains +1 Trade Route capacity with Political Philosophy. Domestic Trade Routes provide +2 Gold and +1 Culture. Roads built inside Persian territory are one level more advanced than usual.",
        unitId: 15,
        buildingId: 48,
    },
    {
        name: "Phoenicia",
        icon: "../imgs/Phoenician.webp",
        ability_name: "Mediterranean Colonies",
        ability: "Starts with the Eureka for Writing. Coastal cities founded by Phoenicia and in the same continent as their Capital always have full Loyalty. Settlers receive +2 Movement and Sight while embarked, and pay no Movement costs to embark or disembark.",
        unitId: 1,
        buildingId: 24,
    },
    {
        name: "Poland",
        icon: "../imgs/Polish.webp",
        ability_name: "Golden Liberty",
        ability: "Building an Encampment or Fort triggers a Culture Bomb, claiming surrounding tiles. One Military policy slot in all governments is converted into a Wildcard policy slot.",
        unitId: 45,
        buildingId: 6,
    },
    {
        name: "Portugal",
        icon: "../imgs/Portuguese.webp",
        ability_name: "Casa da Índia",
        ability: "International Trade Routes can only be sent to cities on the coast or with a Harbor, but gain a +50% increase to all yields. Traders have +50% range over water, and can embark as soon as they are unlocked.",
        unitId: 43,
        buildingId: 10,
        //buildingId: 35,
    },
    {
        name: "Rome",
        icon: "../imgs/Roman.webp",
        ability_name: "All Roads Lead to Rome",
        ability: "Founded or conquered cities start with a Trading Post and, if within Trade Route range of the Capital, a road to it. Trade Routes generate +1 additional Gold from Roman Trading Posts they pass through.",
        unitId: 16,
        buildingId: 31,
    },
    {
        name: "Russia",
        icon: "../imgs/Russian.webp",
        ability_name: "Mother Russia",
        ability: " Founded cities start with five additional tiles. Tundra tiles provide +1 Faith and +1 Production, in addition to their usual yields. Units are immune to damage from Blizzards. +100% damage from Blizzards inside Russian territory to civilizations at war with Russia.",
        unitId: 46,
        buildingId: 20,
    },
    {
        name: "Scotland",
        icon: "../imgs/Scottish.webp",
        ability_name: "Scottish Enlightenment",
        ability: "Happy cities gain +5% Science and +5% Production, and generate +1 Great Scientist point in their Campuses and +1 Great Engineer point in their Industrial Zones. Ecstatic cities double these bonuses.",
        unitId: 48,
        buildingId: 36,
    },
    {
        name: "Scythia",
        icon: "../imgs/Scythian.webp",
        ability_name: "People of the Steppe",
        ability: "Building a light cavalry unit or Saka Horse Archer grants a free second copy of that unit.",
        unitId: 18,
        buildingId: 41,
    },
    {
        name: "Spain",
        icon: "../imgs/Spanish.webp",
        ability_name: "Treasure Fleet",
        ability: "May form Fleets and Armadas with Mercantilism, instead of Nationalism and Mobilization. Trade Routes receive +3 Gold, +2 Faith and +1 Production. Trade Routes between multiple continents receive triple these numbers. Cities not on your original Capital's continent receive +25% Production towards Districts and a Builder when founded.",
        unitId: 38,
        buildingId: 43,
    },
    {
        name: "Sumeria",
        icon: "../imgs/Sumerian.webp",
        ability_name: "Epic Quest",
        ability: "Capturing a Barbarian Outpost also grants a Tribal Village reward. Levying city-state units costs 50% less Gold.",
        unitId: 11,
        buildingId: 55,
    },
    {
        name: "Sweden",
        icon: "../imgs/Swedish.webp",
        ability_name: "Nobel Prize",
        ability: "+50 Diplomatic Favor upon recruiting a Great Person. +1 Great Engineer points from Factories and +1 Great Scientist points from Universities. Sweden's presence in the game adds three unique World Congress competitions in the Industrial Era.",
        unitId: 37,
        buildingId: 11,
        buildingId: 45,
    },
    {
        name: "Vietnam",
        icon: "../imgs/Vietnamese.webp",
        ability_name: "Nine Dragon River Delta",
        ability: "Land specialty Districts can only be built on Woods, Rainforest or Marsh tiles. Buildings on these features receive additional yields: +1 Culture in Woods, +1 Science in Rainforest, and +1 Production in Marsh. Can plant Woods with Medieval Faires, instead of Conservation.",
        unitId: 35,
        buildingId: 22,
    },
    {
        name: "Zulu",
        icon: "../imgs/Zulu.webp",
        ability_name: "Isibongo",
        ability: "Capturing a city will upgrade the conquering unit into a Corps or Army, if the necessary civics are unlocked. +3 Loyalty per turn to cities with a garrisoned unit, increasing to +5 if the garrisoned unit is a Corps or Army.",
        unitId: 26,
        buildingId: 21,
    }
]

const seedCivs = () => Civ.bulkCreate(civData)

module.exports = seedCivs