const { Unit } = require('../models')

const unitData = [
    {
        name: "Bireme",
        icon: "../imgs/Bireme.webp",
        description: "A bireme is a rowed vessel with two banks of oars for rowers arranged in upper and lower decks and armed with a bow ram. The Phoenicians were the foremost shipbuilders of the ancient world and are generally credited by most archaeologists and historians with creating the bireme design, even though the word “bireme” is Latin. The Phoenicians were also perfectly willing to build warships for anyone with ready cash, whether the Greek city-states, or the Persians, or any other Mediterranean power. Naval engagements in the ancient world consisted of trying to run down the other side's ships with a bronze-wrapped bow ram while avoiding being rammed in turn, or getting entangled in a sinking ship and being dragged to a watery doom. Ancient sources use adjectives like “chaotic” and “frenzied” and “terrifying” to describe these naval battles, which seems entirely justified. Archaeological evidence attests to a common practice of painting eyes on the bows of many ships to ward off evil.",
        ability: "Prevents friendly Traders within 4 tiles from being plundered as long as they are on a water tile. Higher Strength Combat Strength (35 vs. 30). Higher Moves Movement (4 vs. 3)."
    },
    {
        name: "Eagle Warrior",
        icon: "../imgs/Eagle_Warrior.webp",
        description: "One of the two elite class of infantry (the other being the Jaguar Warriors) in the Aztec army, the Eagle Warriors were the bravest young men of noble birth and/or those who had taken the most prisoners in battle. Like the Jaguars, the Eagles used the atlatl, bow, spear and macuahuitl (wooden swords set with obsidian shards); unlike the Jaguars, the Eagles decorated their armor with eagle feathers and wore a headdress shaped like the head of an eagle with the beak wide open. And they had a hilltop temple in Malinalco. Upon taking 20 prisoners – intact enough to serve as human sacrifice – a young warrior was eligible to become an Eagle Warrior, no doubt making his family very proud. Until the Spanish arrived with their cannons, muskets, and horses, the Eagle and Jaguar warriors were the toughest bullies on the Mesoamerican block.",
        ability: "Can capture defeated enemy units, turning them into Builders for the Aztecs. Higher Combat Strength (28 vs. 20). Higher Production cost (65 vs. 40)."
    },
    {
        name: "Gaesatae",
        icon: "../imgs/Gaesatae.webp",
        description: "The Gaesatae were Celtic warriors from the Alps. In the early days of the Roman Republic, Rome was expanding northward, taking formerly Gallic land and giving it to poorer Roman families. Worried about this expansion, a group of tribes from Cisalpine Gaul – the northern part of Italy – banded together and hired the Gaesatae to defend them. Armed with spears and javelins, the Gaesatae (according to Greek historian Polybius) fought naked, with nothing but their weapons. Polybius writes that the Gallic army made a “dreadful din, for there were innumerable horn-blowers and trumpeters, and, as the whole army were shouting their war-cries at the same time, there was such a tumult of sound that it seemed that not only the trumpets and the soldiers but all the country round had got a voice and caught up the cry. Very terrifying too were the appearance and the gestures of the naked warriors in front, all in the prime of life, and finely built men.” The strange Gallic costume (or lack of costume) may have been because of their sheer confidence in battle or may have just been a practical measure to keep from getting caught in the brambles. Regardless of why they fought nude, the Gauls won the first few battles, but a better-prepared Rome won the war. Perhaps armor was a good idea after all.",
        ability: "+10 Combat Strength when fighting units with a higher base Combat Strength. +5 Combat Strength when fighting against District defenses."
    },
    {
        name: "Hoplite",
        icon: "../imgs/Hoplite.webp",
        description: "Give a bunch of citizen-soldiers ten-foot iron-headed spears (called doru), put them in a tight formation shoulder-to-shoulder, and the hoplite phalanx appears. In the 8th or 7th century BC, the Greek city-states first began to raise hoplite units – composed of those “free” citizens who could afford the bronze armor and the doru – for fighting among themselves. As the Persians found out, hoplite phalanxes were pretty effective against others as well. Although enemy archers might pick off a few (most of the arrows of the time were too light to penetrate the bronzewear of the Greeks), a phalanx of hoplites could generally sweep everything from the field in front of them; the greatest threat came from exposing their flanks, or losing formation moving over rough ground. The hoplite-phalanx survived for almost 400 years, through the age of Alexander the Great still dominant, until it came up against the Roman legion, faster afoot, more flexible in formation, and more adept with their short swords once they slipped past those unwieldy spears.",
        ability: "+10 Combat Strength when adjacent to at least one other Hoplite. Higher Combat Strength (28 vs. 25)."
    },
    {
        name: "Hul'che",
        icon: "../imgs/hulche.webp",
        description: "The hul’che, a Mayan weapon for throwing a dart or arrow, seems at first to be quite simple. It is a long wooden shaft with a notch at the end, where an arrow sits. Used by an experienced marksman, the hul’che greatly increases the force of a throw, throwing a dart at over three hundred miles per hour (150 meters per second). Against lightly armored Mesoamerican soldiers, the hul’che would have been deadly. It was used in many ancient societies: the Aztec called it the atlatl, Australian aboriginal groups called theirs a woomera, and archaeological evidence for similar devices exists across Europe. Both Maya men and women were trained in the use of the hul’che. Mayan battles would begin with an exchange of hul’che darts, wounding opponents before individual melee fighters rushed in in a search for individual glory.",
        ability: "+5 Strength Ranged Strength against wounded units. Higher Strength Ranged Strength (28 vs. 25)."
    },
    {
        name: "Maryannu Chariot Archer",
        icon: "../imgs/Maryannu_Chariot_Archer.webp",
        description: "The maryannu (the singular form marya, meaning “young warrior” or “youthful hero”) was a hereditary caste of chariot-mounted nobility, found in several societies in Bronze Age Middle East. In Egypt, they rode in two-man light chariots, which offered a more stable base for archery than did horseback, given the length of the bows common at the time. And the marya could carry more ammunition. But there were some significant disadvantages for the young heroes such as the limitations of terrain and the maintenance of the vehicle and horses on long campaigns. Nonetheless, the maryannu were a powerful elite in the pharaoh’s army; the best record of their effectiveness in battle is at Kadesh, c. 1274 BC, where they carried the day for Ramesses II. There are lots of images left behind depicting the ancient Egyptian maryannu chariots (one of the indelible images of that civilization), and six well-preserved specimens were found in the tomb of Tutankhamun (who passed over around 1323 BC).",
        ability: "Ignores enemy zone of control. +2 Movement when starting its turn on flat terrain with no Woods or Rainforests. Has a ranged attack with Range 2. -17 Ranged Strength vs. District defenses and naval units. Higher Production cost (120 vs. 65) Higher Gold maintenance cost (2 vs. 1). Lower Combat Strength (25 vs. 28)."
    },
    {
        name: "Okihtcitaw",
        icon: "../imgs/Okihtcitaw.webp",
        description: "Roughly translating to “warrior,” the okihtcitaw had a much more important role within Cree society than merely serving as combatants. The sons of chiefs, they protected the tribe when it traveled and kept order when it settled. They also policed buffalo hunts to ensure that no one hunter began before any other. The Cree considered these seasoned warriors incredibly brave and skilled in combat, a step above their peers—often charismatic and clever, allowing them to serve as effective leaders in times of war and peace.",
        ability: "Receives one free Promotion when first trained or purchased. Higher Production cost (40 vs. 30). Higher Combat Strength (20 vs. 10)."
    },
    {
        name: "Pítati Archer",
        icon: "../imgs/pitati_Archer.webp",
        description: "The skill of Nubian archers was long respected and feared along the Nile. These soldiers from the Land of the Bow were a thorn in Egypt’s side for millennia—until the Egyptians solved yet another problem by throwing money at it. Thus came about the pítati, Nubian mercenaries paid well to guard the interests of their benefactors, be they Egyptian or Nubian. These highly mobile archers wore little armor and carried bows typical to the region. However, their distinctive thumb rings greatly reduced fatigue, and malachite facepaint applied below their eyes allowed them to loose arrows with accuracy while firing into the sun.",
        ability: "Higher Combat Strength (17 vs. 15). Higher Strength Ranged Strength (30 vs. 25). Higher Movement (3 vs. 2). Higher Production cost (70 vs. 60)."
    },
    {
        name: "Sabum Kibittum",
        icon: "../imgs/Sabum_Kibittum.webp",
        description: "After Hammurabi’s time, Babylon was occupied by the Assyrians, who reshaped Mesopotamian warfare. The Assyrian king Tiglath Pileser III took up what was originally a collection of conscripted farmers and made from them an integrated army, with different units taking up different tasks (e.g. supply lines, communication, engineering, etc). Further, the Assyrian troops used iron weapons, when most of their contemporaries were still using bronze. The Assyrian sabum kibittum – shock troops – would have been terrifying. What they left behind certainly was; in their monuments, Assyrian kings repeated, “I destroyed, I devastated, and burned with fire.”",
        ability: "+5 Combat Strength vs. anti-cavalry units. +17 Combat Strength vs. heavy and light cavalry units. High Movement. High Sight."
    },
    {
        name: "Viking Longship",
        icon: "../imgs/Viking_Longship.webp",
        description: "'A furore Normannorum libera nos, Domine.' The famous prayer, usually uttered by hapless folk upon first sight of the sails of the Vikings’ longships, sums it up. From Ireland to the walls of Paris, the longships carried the fierce Norsemen to kill and plunder. But they also carried Norse explorers across the North Atlantic to Iceland, Greenland, and North America. And traders as far as Rome and Constantinople. Indeed, the longships were the apex of European naval design from the 9th through 13th centuries. Viking longships came in various types; by far the most infamous is the drekkar, a graceful, narrow, shallow-draft vessel, ornately decorated (dragons and snakes and the like), used primarily by those who went raiding. Not only were the drekkar able to sail deep waters, but their shallow draft meant these could navigate up rivers … useful in pillaging cities like Paris.",
        ability: "Can perform Coastal Raids. +1 Movement while in coastal waters. Ignores enemy zone of control. Higher Combat Strength (35 vs. 30)."
    },
    {
        name: "War-Cart",
        icon: "../imgs/War-Cart.webp",
        description: "The nigh constant wars (more like backwood feuds than armed conflicts) between the Sumerian city-states helped develop a couple of innovations in killing that would spread across the ancient world. The first battle ever recorded for posterity was between Lagash and Umma c. 2525 BC as depicted on the “Stele of Vultures.” Among other things of interest, the stele shows the commander Eannatum riding in a “chariot” – actually, more a four-wheeled cart pulled by asses (the animals, not the humans). The Sumerian war-cart was a four-wheeled device composed of a woven basket mounted on wooden, solid wheels; it was manned by a crew of two carrying battle-axes and lances and pulled by a yoke of four onagers (those Asiatic asses). Although shown on this and other stele, there is considerable debate as to whether the war-carts were actually used in combat, or served more as a “battle taxi,” carting the commander around to strategic locations where he could dismount and lead his troops personally in the melee. Whatever the function, the Sumerian war-cart was the genesis for the later horse-drawn war chariot.",
        ability: "Strongest of the starting units in the game. No combat penalties against anti-cavalry units. +1 Movement when starting its turn on flat terrain with no Woods or Rainforests. Ignores enemy zone of control."
    },
    {
        name: "Dromon",
        icon: "../imgs/Dromon.webp",
        description: "The Byzantine navy had some of the most advanced ships in the Mediterranean. Abandoning an earlier reliance upon a trireme with a ram in its prow, the dromon had a “beak” (calcar), a projection at the ship’s front that served as a bridge for soldiers to cross onto enemy ships (or, alternately, to crush the enemy’s oars). Along with the triangular sail and one or multiple banks of oars, the dromon was fast and maneuverable, and deadly. But the dromon’s most fearsome feature was its fire. “Greek fire,” a mixture of oil and quicklime, was a concoction that burned even when floating on water. Some dromons had Greek fire projectors at their bow: essentially a medieval ship-mounted flamethrower. This weapon was used to great effect to repel Arab sieges of Constantinople as well as, famously, an invasion of Rus (Viking raiders from what is now Russia) during the reign of Emperor Romanus. In one contemporaneous account, the Rus, when they saw the flame cannons, “threw themselves from their ships into the sea, choosing to be drowned by the waves rather than cremated by the fire… No one escaped that day unless he was able to flee to the shore.”",
        ability: "+10 Combat Strength against land and naval units. Has a ranged attack with Range 2."
    },
    {
        name: "Hetairoi",
        icon: "../imgs/Hetairoi.webp",
        description: "The powerful hetairoi (known simply as “the Companions”) were an elite cavalry unit who served as the hammer in Macedon’s famed hammer-and-anvil tactics, popularized under Philip II and used to great effect by his son, Alexander the Great. While the Macedonian phalanx pinned a rival army in place with their extra-long spears (known as sarissas), the hetairoi would organize into a wedge and charge directly into the enemy flanks or rear. An abrupt attack by the shock cavalry nearly impossible to avoid or deter, and was often enough to break the will of less seasoned troops. As they fled for their lives, they were easy pickings for the hetairoi who could ride them down and dispatch them in their leisure. Most of the Companions came from the ranks of Macedon’s noble families, though the king could technically admit anyone to their ranks. They were armed with short spears and swords.",
        ability: "+5 additional Combat Strength when attacking a unit adjacent to a Great General. +5 Great General points from kills. Receives one free Promotion when first trained or purchased."
    },
    {
        name: "Hypaspist",
        icon: "../imgs/Hypaspist.webp",
        description: "Among the Greeks, a hypaspist (or “shield bearer”) was a lightly-armored soldier who possessed great flexibility on the battlefield. Philip II of Macedon turned them into legends. The Macedonian phalanx, while very nearly impregnable, was most vulnerable at its flanks and in its rear. Though the hetairoi (or “Companions”) could help protect against such attacks, their essential role as shock cavalry meant they were best used in a more offensive role. Thus, the hypaspistai. With a solid round shield, linen armor, and a short spear, the hypaspistai could rapidly maneuver to protect against attacks from infantry or cavalry. In turn, the hetairoi would protect the hypaspistai, providing progressively flexible flanks around an exceptionally spiky and slow-turning center. Philip’s elevation of the hypaspistai stressed the importance of maintaining the phalanx, and in turn provided an elite unit for young soldiers of Macedon to aspire. His son Alexander the Great would continue Philip’s tradition.",
        ability: "+5 Combat Strength when besieging a District. Increased support bonus (3 vs. 2). Higher Combat Strength (38 vs. 35). Higher Production cost (100 vs. 90)."
    },
    {
        name: "Immortal",
        icon: "../imgs/Immortal.webp",
        description: "The elite heavy infantry of the ancient Persian Empire has a fearsome reputation, but much that is known of them comes from the writings of Herodotus, whose accounts were widely read but not necessarily accurate. For example, the very name by which they are known—the Immortals—was of Greek origin, not Persian. According to Herodotus, they were said to maintain a force of exactly 10,000 soldiers who, upon injury or death, were immediately replaced so they would never be anything less than full strength. As elite troops they were afforded special luxuries, such as their own food kept separately from the rest of the army. Their clothes were vibrant, covering coats made of armored metal scales, and they carried a variety of armaments such as short spears, swords, and powerful bows. Whatever their actual disposition, they were respected (and feared) by their contemporaries.",
        ability: "Has a ranged attack (25 Ranged Strength, 2 Range). Can still make melee attacks. -17 Ranged Strength against District defenses and naval units."
    },
    {
        name: "Legion",
        icon: "../imgs/Legion.webp",
        description: "The legion was the most efficient and effective fighting force in history...well, in its time anyway. A fully-equipped, fully-staffed Roman legion could march across any terrain, laying a road as it did, built a fortified camp at the end of it, and then take any foe or take any wall. During the Empire a legion was composed of infantry, recruited exclusively from Roman citizens, along with the cooks, armorers, engineers, artillerists, medics and command staff (as well as the usual camp followers and sutlers) necessary to operate in the field for years at a time. The light infantry, archers, scouts, and cavalry were generally auxiliaries, provincial non-citizens (those who survived to be honorably discharged gained citizenship) assigned to a legion as necessity dictated. Extremely disciplined (usually), the legion’s heavy infantry were armed with pilum (throwing spear) and gladius (short sword) and conquered most of the known world (granted, a bunch of barbarians and decaying empires) at the time.",
        ability: "Has 1 Build charges. Can construct a Roman Fort. (Consumes build charge.) Can clear terrain. (Consumes build charge.)"
    },
    {
        name: "Ngao Mbeba",
        icon: "../imgs/Ngao_Mbeba.webp",
        description: "The Kingdom of Kongo’s army was a mass of archers with a smaller contingent of heavy infantry, which carried swords and shields. The colonial Portuguese referred to the latter in their accounts as adagueiros (“shield-bearers”) while in the few surviving native documents the Swahili term ngao mbeba is used. While the archers were militia conscripts in time of war, there is some evidence that the standing ngao mbeba were supported by stipends from the king. Perhaps as many as 20 thousand were garrisoned in the capital, with smaller contingents in the provinces under the command of the local authority. Under king Afonso I, a small unit of Portuguese-armed native musketmen was raised, and eventually the old shield-bearers were replaced by the deadlier youngsters.",
        ability: "Does not suffer Movement or sight penalties in Woods or Rainforests. +10 Combat Strength when defending against ranged attacks."
    },
    {
        name: "Saka Horse Archer",
        icon: "../imgs/Saka_Horse_Archer.webp",
        description: "The term “Saka” may refer to the Persian and Sanskrit word for the Scythians, or it may refer to a specific tribe among those horse-barbarians to the north of Assyria. Most of the confusion seems to be the ambiguous usage of Saka among the ancient “historians” – Herodotus, Strabo, Pliny the Elder, and that lot. Herodotus states that the Saka were horse archers, riding without saddles or stirrups, and distinguished by wearing quilted trousers, open tunics and “high caps tapering to a point and stiffly upright.” These horse archers were feared in the open, mostly for harassing a moving column or raiding the baggage trains, but not very good in a stand-up fight. As Alexander the Great had shown at the battle of Jaxartes (329 BC) the Saka had no staying power, and could be readily driven off by massed infantry in depth supported by ample numbers of foot archers, whose greater range and rate of fire gave them a distinct advantage over the mounted ones.",
        ability: "Has a ranged attack with Range 1. Ignores enemy zone of control. -17 Ranged Strength against District defenses and naval units."
    },
    {
        name: "Toa",
        icon: "../imgs/Toa.webp",
        description: "The Maori word Toa translates simply as “warrior” when used as a noun, and “to win” when used as a verb. In Maori culture, the concept of utu implies that behaviors should be balance, with positive behaviors and gifts rewarded, and wrongs punished to a proportional extent. The Maori culture possessed gradations for these responses, from raiding to full violence. Failure by a leader to respond appropriately could bring about a loss of their mana. European observers were particularly impressed (one might even say terrified) by the great strength and energy of the toa they encountered. The toa had some distinctive weapons. The staff-like taiaha is made from hardwood, slightly flattened on one end (called the ate), with a stabbing base end below the hand grip. This is the weapon traditionally used during the wero—the traditional challenge at the beginning of a powhiri welcoming ceremony. The smaller, paddle-shaped mere was made from greenstone, with a wrist cord passing through the handle, and used as a stabbing weapon. Mere were also ceremonial objects, used to indicate the prestige of the bearer, due to the difficulty of their manufacturing. Larger clubs were called patu, and were made of hardwood, stone, or bone. Maori created strong hill forts called Pa, which consisted of terraced land, protected by an elaborate system of palisades and ramparts, encompassing an inner area with access to fresh water and food stores. The introduction of gunpowder weapons and modern artillery eventually rendered these obsolete. Today the toa are best known for the practice of the haka, the terrifying, energetic chant and dance originating as a war dance. Originally performed to indicate the great strength and skill of the toa, they are performed today by both men and women as part of many activities, including sporting events, formal greetings, and weddings.",
        ability: "Reduces the Combat Strength of adjacent enemy units by 5 (non-cumulatively). Has 1 Build charge. Can construct a Pā (Consumes a build charge). Can clear terrain (Consumes a build charge)."
    },
    {
        name: "Varu",
        icon: "../imgs/Varu.webp",
        description: "Although not the most reliable of battle-mounts (as apt to trample friendly troops as enemy when panicked), war elephants were a staple in Indian warfare for centuries until the advent of gunpowder. In pre-gunpowder combat, the 'vāru' (“royal elephant”) served two purposes. Their scent tended to terrify horses, thus rendering the enemy cavalry relatively useless. Second, they could usually break through even the strongest line of infantry, especially if armored, crushing spearmen and archers and everything else in their path (and reaching 25 kph on the run). Too, elephants were notoriously hard to kill, and there are records of them surviving as many as sixty arrows. Usually surmounted with a howdah or other platform for archers, the vāru could wade right into the fray. But, in case the elephants did go berserk and start squashing their own side, the driver carried a spike and mallet to kill them with a blow to the skull.",
        ability: "Ignores enemy zone of control. Reduces the Combat Strength of adjacent enemy units by 5 (non-cumulatively; cumulatively under other rulesets)."
    },
    {
        name: "Barbary Corsair",
        icon: "../imgs/Barbary_Corsair_29.webp",
        description: "The Barbary Corsairs were some of the most feared and famous pirates of the Mediterranean during the Renaissance and Early Modern era. These pirates were financed and sanctioned by the Ottoman Empire, in much the way Western European states used privateers as commercial raiders. As the Ottoman Empire expanded and came into conflict with Western Europe, raids by the corsairs became more common. At the height of their power, the sight of a sleek corsair galley (or more terrifying, a fleet of them) bearing down was enough to fill the sight of all but the bravest of captains with a deep dread. Piracy was a long-standing practice in the Mediterranean Sea, almost from the start of recorded history. The Barbary Corsairs were among the last of these groups, raiding all along the European coast. Operating from fortified ports along the Berber coast, like Algiers and Tunis, the Barbary Corsairs were famous for capturing ships and holding their crews for ransom—and often enslaving those too poor to be ransomed. Literature from the period is full of tales from escaped galley slaves, and a whole charitable industry arose out of liberating prisoners from the corsairs. But some Europeans found the prospect for riches and power attractive, and voluntarily joined the corsairs' ranks, and even served as officers.",
        ability: "Uses no Movement to perform coastal raids. Lower Production cost (240 vs. 280). Lower Gold maintenance cost (3 vs. 4)."
    },
    {
        name: "Berserker",
        icon: "../imgs/Berserker.webp",
        description: "According to a number of Old Norse sources, the berserkers (Ulfhednir or “Odin’s special warriors”) were Vikings who fought in “an uncontrollable, trance-like fury.” Other sagas note they forsook armor and went into battle bare-chested wearing wolf pelts, and were “mad as hounds, bit their shields … they slew men but neither fire nor iron had effect upon them.” Pretty impressive, even to the other fun-loving Norsemen. King Harald Fairhair supposedly used them as shock troops in the front ranks of his army c. 800 AD, and other Norse kings kept some as royal bodyguards, depending on their fierce reputation to keep the unruly in line. As the pious Christians said, “From the fury of the Norsemen, good Lord, deliver us.”",
        ability: "+2 Movement when starting its turn in enemy territory. +10 Combat Strength when attacking. -5 Combat Strength when defending against melee attacks. Higher Combat Strength (48 vs. 45)."
    },
    {
        name: "Black Army",
        icon: "../imgs/Black_Army.webp",
        description: "The Black Army of Matthias Corvinus was one of the first professional state military forces of Europe, and is important not only because of their impressive battlefield record, but because they presaged many of the reforms associated with state control of armed forces centuries before this would become the norm. They were one of the first European armies to make extensive use of the new gunpowder weapons, including bombards and the arquebus, with a higher proportion of gunners than any army until late into the Renaissance. The Black Army also possessed excellent heavy and light cavalry, and the Black Army marks the first use of the term “hussar” to refer to these light cavalry forces. Their name is said to come from the color of their armor. Medieval armies can be loosely classified between feudal and mercenary armies. Feudal forces were raised and commanded by nobles on behalf of their sovereign. Generally only the nobility had any significant experience in warfare, and long-standing laws prevented the feudal armies from being fielded for very long. Mercenary forces were generally seen as better-trained, but were more expensive to maintain. A ruler failed to pay his mercenaries to his considerable peril—mercenaries frequently switched sides or revolting against their employers over delayed or missing payment. The Black Army was a mercenary army, because it employed professional soldiers from within and beyond Hungary. Matthias Corvinus had studied the legions of the Roman Empire, and had conceived of the Black Army in similar terms—professional soldiers who acted at the direction of the sovereign, and who were paid through state taxes. In this case, the nobility and population were extensively taxed. An army as large and well-equipped as the Black Army was expensive to field. At its height, the Black Army was larger than the armies of France, and compiled an excellent record in battle and siege. The Black Army did not last long after Matthias' death. His successors were unable to sustain the taxation system that paid the army, and it gradually declined in quality and size. By the time of the disastrous Battle of Mohacs, Hungary's armies had returned to the old feudal model, and were utterly crushed by the Ottoman Empire, which was using weapons and tactics that would have been recognizable to the captains of the Black Army.",
        ability: "+3 Combat Strength for each adjacent Levied unit. Higher Combat Strength (49 vs. 46). Higher Production cost (205 vs. 200)."
    },
    {
        name: "Crouching Tiger",
        icon: "../imgs/Crouching_Tiger.webp",
        description: "After the Chinese discovered gunpowder c. 9th Century AD, they used it just for fireworks and making pretty, colorful explosions. But eventually someone figured out it was pretty useful in warfare too, and soon enough flintlocks and cannon were all the rage in Asia. According to Dr. Yongxiang Lu, the little-known Chinese “Crouching Tiger” lay somewhere between a bombard and a cannon, one of the earliest uses of gunpowder in warfare. A crude device, it was basically an iron tube, sealed at one end, wrapped with thick ropes to reinforce it and with two short legs at the front to elevate the barrel slightly (so the shot didn’t plow up the ground instead of smashing the enemy). It is known that the Crouching Tiger saw action c. 1368 at the beginning of the Ming dynasty, and was still being used as late as 1592 against the Japanese in Korea. When fired, it is reported to have had a range of about 800 paces, which no doubt made the enemy very uncomfortable since it outranged anything else at the time.",
        ability: "High Ranged Strength. Has a ranged attack with Range 1. -17 Ranged Strength against District defenses and naval units."
    },
    {
        name: "Domrey",
        icon: "../imgs/Domrey.webp",
        description: "If there aren't enough horses for your cavalry, why not use the mighty elephant to crush and terrify your enemies? The Khmer joined a long tradition of employing war elephants in their military campaigns. Research suggests that the Indians first used elephants in their military campaigns around 1,100 BCE, tuning what was at that point a farming helper animal and turning its 12,000 pounds of might into sound and terror for their opponents on the battlefield (at least until the invention of gunpowder evened the odds). The mount of kings, military leaders would ride elephants into the battlefield, using their lines to stampede through enemy forces. Khmer riders would use the precision of double crossbows to supplement the raw power of their elephants. However, this domrey variant adds a bit more sheer force with a mounted ballista to impale the bold soldier not wise enough to run away.",
        ability: "Can move and attack on the same turn. Exerts zone of control. Higher Combat Strength (40 vs. 35). Higher Bombard Strength(50 vs. 45)."
    },
    {
        name: "Impi",
        icon: "../imgs/Impi.webp",
        description: "The powerful warrior regiments of the Zulu were already a formidable force when the ambitious Shaka taught them new techniques: combining the iklwa (a short, stabbing spear with a broader blade than a throwing spear) and the ishlangu (a large, oval shield with cowhide layered on top). They trained to form shield walls, both to blunt projectiles and to hide their true numbers, and attack with a “buffalo horns” formation—greener troops would sweep out and around to pin the enemy’s flanks (the horns), while a more experienced center would slam into the pinned enemy (the rest of the buffalo). The impi training regimes under Shaka were nothing less than brutal, but harsh conditioning led to tightly bonded, well-disciplined soldiers able to carry out complex formations with ease. The impi became a highly mobile force, nigh-unstoppable against anything short of repeating rifles and high explosives.",
        ability: "Gains 25% more experience. Lower Production cost (125 vs. 200). Lower Gold maintenance cost (1 vs. 3). Increased flanking bonus (4 vs. 2)."
    },
    {
        name: "Jong",
        icon: "../imgs/Jong.webp",
        description: "If you wish to dominate the high seas, confront the enemy with overwhelming force. This was the philosophy behind the massive jong ships, the schooner of the Majapahit. This vessel allowed the Empire to control Javanese waters through a combination of size and strength. The Majapahit sailing vessels differentiated themselves from Chinese junks with the addition of a second rudder, which made the 600 ton jong fast yet easy to control. This wasn't the only extra maneuverability option for the jong; if the winds were low, a row of oarsmen could move the schooner beyond the range of enemy fire or around seaborne obstacles. While primarily used as merchant ships, jongs also served as military transports. All of that weight wasn't just for show: the addition of four-layer wooden masts offered protection against incoming cannon fire, and a jong under attack could return the favor with its own opposing ordnance.",
        ability: "When in formation, gains +5 Combat Strength and shares its Movement with all units in the formation. No strategic resource requirement. Higher Movement (5 vs. 4). Higher Production cost (300 vs. 280)."
    },
    {
        name: "Keshig",
        icon: "../imgs/Keshig.webp",
        description: "The Mongolian keshig were the elite imperial guard of the Great Khan. These mounted warriors, originally comprised of Genghis Khan’s most loyal fighters, grew to 10,000 strong among later khans. The keshig were well equipped, using their composite bows and mobility to harry opponents from a distance. As horse archers, they were second to none. Their peculiar rank as the Khan’s guard put them above even the commanding officers of an army—unsurprising, for they were predominantly composed of young warriors from prominent households.",
        ability: "High Movement. Ignores enemy zone of control. Has a ranged attack with Range 2. When in formation, shares its Movement with all units in the formation. -17 Ranged Strength against District defenses and naval units."
    },
    {
        name: "Khevsur",
        icon: "../imgs/Khevsur.webp",
        description: "The warriors from Georgia’s Khevsureti territory maintained their traditions for countless generations. (Until the early 20th Century, they continued to fight with weapons and armor more suited to medieval times.) These fierce Georgians dressed in chainmail and carried swords, axes, and small, black bucklers adorned with crosses for nighttime raids—due to the shield’s color, the warriors were practically invisible in the moonlight. Though tradition was their watchword, they did adapt with the times, incorporating firearms as their importance on the battlefield became unmistakable.",
        ability: "No Movement penalty in Hills. +7 Combat Strength when fighting in Hills. Higher Combat Strength (48 vs. 45)."
    },
    {
        name: "Mamluk",
        icon: "../imgs/Mamluk.webp",
        description: "Although the term mamluk simply means “property” or “owned slave” in Arabic, most think of the military caste in medieval Islam as the only mamalik (the plural form) in history. They are certainly the most famous. Although there is disagreement among scholars, most agree that the mamluk slave-warriors arose during the reign of the Abbasid caliphs of Bagdad sometime around the 9th Century AD. These warriors were primarily of Kipchak, Circassian, Georgian, and Balkan tribes, captured or sold into slavery, and proved devoted converts to Islam, superb horsemen, and vicious adversaries. Over time the mamluks became a political power – as in Cairo where they established a sultanate – in many Muslim kingdoms, where they sometimes served as kingmakers (well, sultan-makers). So successful and influential was the mamluk caste that it survived 1000 years until wiped out by the Ottoman general Muhammad Ali Pasha in 1811.",
        ability: "Heals at the end of every turn, even if it moves or attacks."
    },
    {
        name: "Mandekalu Cavalry",
        icon: "../imgs/Mandekalu_Cavalry.webp",
        description: "Mandekalu cavalrymen were the elite of Malinese society, as horses were a rare and expensive commodity south of the Sahara. The Mandekalu cavalryman was armed with lance and sword, and was equipped with mail and an iron helmet. This need for armor and weapons created a cultural alliance between skilled Malian blacksmiths (working iron was a rare art, kept secret) and the nobility who used the weapons and armor in battle. Mansa Sundiata is generally credited with organizing the cavalry into their own branch of the army. In the Sahel—the arid grasslands south of the Sahara—the mobility and shock power of the cavalry made them a fearful enemy, and they were key to the Malian military expansion. As the weather got warmer and wetter during the 15th and 16th century, the tsetse fly ranged farther, spreading diseases among horses and riders, and generally reducing the effectiveness of the Mandekalu. At the same time, declining woodlands reduced the supplies of wood for charcoal, making the traditional iron weapons more expensive to manufacture.",
        ability: "Prevents friendly Traders within 4 tiles from being plundered as long as they are on a land tile. Provides Gold equal to 100% of the base Combat Strength of each defeated enemy unit. Higher Combat Strength (55 vs. 50)."
    },
    {
        name: "Oromo Cavalry",
        icon: "../imgs/Oromo_Cavalry.webp",
        description: "The word “Oromo” refers to the dominant ethnic group in Ethiopia, making up about a third of the total population. The Oromo at times had their own kingdom, language and religion (although in present-day Ethiopia they are evenly split between Muslims and Christians). During the First Italo-Ethiopian War, when Italy attempted to seize Ethiopia as a colonial possession, the Ethiopian emperor Menelik used Oromo cavalrymen to devastating effect, especially in the decisive Battle of Adwa. The Oromo cavalry were not true cavalry, but mounted infantrymen, meaning that they did not fire weapons from horseback, but would gallop towards the Italians, dismount, and then fire. With their lion’s-mane headdresses and fierce reputation, they became one of the most feared military units of the era. During the Italian invasion, a rumor spread around the Italian camps that Oromo cavalry (whom the Italians called “Galla” – a word that was seen as offensive by the Oromo) would castrate the bodies of enemies that held weapons – a rumor that caused many Italians to toss aside their guns the moment that the Oromo began their charge. Italian soldiers reported their compatriots turning their guns on themselves rather than facing the Oromo. One report depicts a lone Italian survivor of an Oromo attack, dazed out of his mind, unable to say anything but “Galla cavalry. Galla cavalry. Horror. Horror.”",
        ability: "No Movement penalty in Hills. Higher Sight (3 vs. 2). Higher Combat Strength (48 vs. 46)."
    },
    {
        name: "Samurai",
        icon: "../imgs/Samurai.webp",
        description: "Until the ‘ashigaru’ (peasant) infantry were armed with muskets, the samurai (“those who serve in close attendance”) dominated warfare and politics in Japan for nearly a thousand years. Although the roots lie in the Nara period, it was during the Heian period c. 800 AD that bushido (“the way of the warrior”) was codified and a number of noble clans adopted its philosophies. By the time of the Heiji Rebellion of 1160, the samurai clans dominated the landscape, with various factions fighting over the shogunate, defeating the Mongol invasion, and otherwise building an impressive historical legacy of fact and myth. Throughout the Edo period, Japan was unified and at peace, and so the samurai became refined - writing poetry, attending kabuki theater productions, and engaging in the sorts of intrigue that one would expect from a bored and pampered class of would-be warriors. Unfortunately, the Emperor Meiji instituted a number of reforms in 1868 – including the end of the shogunate and abolition of the samurai class.",
        ability: "Does not suffer combat penalties when damaged. Higher Strength Combat Strength (48 vs. 45)."
    },
    {
        name: "Tagma",
        icon: "../imgs/Tagma.webp",
        description: "The tagma – plural: tagmata – were the Byzantine descendants of the Roman imperial guard. At first, the tagmata were noble young men who sought positions where they could be personally close to the Emperor and perhaps gain his attention. But over time, the imperial guard became more of a social space than a fighting force and, in the 8th century, the Emperor Constantine V sought to reorganize them into a mobile, rapid-response force: the tagma. Tagma units were continually updated and refined, and later emperors brought new inventions in heavy cavalry into the force. The guard grew so successful that, under Basil II, the tagma system expanded to include not just knights in Constantinople, but provincial units and foreigners. These also involved the feared Varangian Guard – Viking mercenaries in the direct employ of the Byzantine Emperor.",
        ability: "Grants nearby land units +4 Combat Strength or +4 Religious Strength."
    },
    {
        name: "Voi Chiến",
        icon: "../imgs/Voi_Chien.webp",
        description: "In Southeast Asian civilizations from Burma to Siam to Cambodia, the elephant is the quintessential symbol of royal power. A Southeast Asian knight astride a war elephant and wielding a long spear would have been a formidable foe, and an elephant with a crossbow on its back could be a deadly and mobile siege weapon. Even with the advent of gunpowder, the high perch that an elephant’s back afforded would give a sharpshooter an impressive tactical advantage. In Vietnam, war elephants - voi chiến – were used to stop the Mongol advance in the 13th century. But the elephant was important in Vietnam long before that, both as a weapon as well as a symbol of power. The Trưng sisters in the first century AD rode elephants into battle in their war of rebellion against the Chinese Han dynasty. Later, Bà Triệu, in yet another conflict with China, is also depicted astride a war elephant. While elephants could resist musket fire, cannons were another story. By the twentieth century, war elephants fell largely out of use, although the Vietnamese still used them to move supplies and troops quickly and quietly through the jungle during wars against the French, United States, and China. Such support elephants are still used today by Kachin rebel groups in Myanmar (former Burma).",
        ability: "Can move after attacking. Higher Combat Strength (35 vs. 30). Higher Movement (3 vs. 2). Higher Sight (3 vs. 2). Higher Production cost (200 vs. 180)."
    },
    {
        name: "Warak'aq",
        icon: "../imgs/Warakaq.webp",
        description: "Literally translated from Quechua, this word means “the one who throws stones with a sling.” Slings have been associated with the Native American civilizations, but most especially with the cultures of the Andes. Even today, Andean herders continue to use the sling to protect their flocks, preserving the ancient heritage of this missile weapon. Inca warriors had access to a variety of weapons, ranging from distinctive bronze maces, hardwood clubs, and spears to javelins, bolas, and the sling. Warriors, particularly those of the upper class, would be well-decorated and elaborately ornamented to impress the enemy, with brightly-decorated fabric tunics and feather headdresses, or equipped with various kinds of padded armor. But the efficacy of slingers made an impression on the Spanish Conquistadors, and they were a common weapon among native uprisings against the Spanish colonists. Andean slings are generally long and most frequently made from llama wool. The braiding is generally done in contrasting colors (black and white are most common). Since herding was a common profession for Incan men, there was a ready pool of manpower accustomed to using the weapon. Archaeologists have uncovered caches of sling stones in fortifications throughout the Andes, indicating careful preparation and consideration for the slingers. The sling is, in many ways, the ideal weapon for the Andes: Ammunition is in ready supply, and the difficult terrain makes more complicated missile weapons an iffy proposition. The sling is portable, easy to construct, and deadly in trained hands, as the Inca's enemies learned to their detriment.",
        ability: "Can make 1 additional attack per turn if Movement allows. Higher Production cost (165 vs. 150). Higher Ranged Strength (40 vs. 30)."
    },
    {
        name: "Carolean",
        icon: "../imgs/Carolean.webp",
        description: "The Caroleans were a new class of soldiers created by the military reforms of Sweden's kings Charles XI and XII. First employed during the Great Northern War, they were distinctive in that they employed shock tactics at a time when most armies used far simpler and less energetic maneuvers in formation. Their tactical innovations they were highly effective against their numerous enemies. The Caroleans used a system called Gå–På—literally “go on”—which is best described as a coordinated effort by the entire battalion to close with the enemy and then hit them as hard as possible in one powerful punch. A Carolean battalion would be armed with a mix of pikes, swords, and muskets with bayonets. They would advance at a jog to within a few dozen meters of the enemy line, pause long enough to fire their muskets once or twice (Swedish muskets were somewhat heavier than those of their rivals), and then charge the enemy while he reloaded. Most armies used the pike to protect the infantry from cavalry attack. The Caroleans used them on the attack because sometimes a bayonet simply wasn't long enough. At the dawn of the 18th Century, these were aggressive, revolutionary tactics. In general, the idea with infantry warfare at the time was to force the other side to retreat, usually by breaking the coherency of the line. Most armies' infantry stood about 100 meters apart and blast away until either the entire battlefield was obscured with smoke, or one side broke morale and fled. The aggressive Caroleans would advance intact through the initial enemy fire, return a higher volume of counterfire, accept the second enemy volley, and then proceed straight to the bayonetting part. Most of the enemies of Sweden preferred to skip the bayonetting altogether, and would break prior to contact with the Caroleans. This is a rational response to a charge by angry, motivated, well-trained Swedes.",
        ability: "+3 Combat Strength per point of unused Movement. Higher Movement (3 vs. 2). Lower Gold maintenance cost (3 vs. 4)."
    },
    {
        name: "Conquistador",
        icon: "../imgs/Conquistador.webp",
        description: "The Spanish conquistadores (“conquerors”) were the soldier-explorers who colonized the world for Spain from the 14th through the 18th centuries. With the end of the Reconquista in 1492 AD, there were a lot of veteran Spanish soldiers at loose ends; luckily, shortly thereafter the Spanish discovered a New World, just ripe for conquest and conversion to Christianity (the latter actually did motivate some). The conquistadors would spread across the Americas, Africa, Asia, and even Oceania, exploring, exploiting, and even settling down in places. Drawn primarily from the ranks of light horsemen, the combination of European tactics, weapons, mounts, and ruthlessness meant most of the natives had little chance of defeating the conquistadors … and that small chance only due to sheer numbers (provided enough of them were willing to die). There is no doubt that without the likes of Cortes, Pizarro, de Balboa, de Soto and others chasing fortune, there would have been no globe-spanning empire.",
        ability: "+10 Combat Strength when escorting (or when within 1 tile of) a religious unit. Converts cities to Spain's majority religion if it captures a city or is adjacent to the city when it is captured. Higher Combat Strength (58 vs. 55). Higher Production cost (250 vs. 240)."
    },
    {
        name: "De Zeven Provinciën",
        icon: "../imgs/De_Zeven_Provincien.webp",
        description: "For a fledgling nation bordering a small patch of the North Sea, the Dutch fleet of the late 17th Century was rather exceptional. Its powerful ships of the line were nearly half the length of a football field (either variety), armed with a minimum of 80 guns spread across two gun decks. A typical Dutch ship of this class was the flagship De Zeven Provinciën (“The Seven Provinces”), the naval backbone of multiple battles in the Anglo-Dutch wars—battles nobody expected a mercantile nation to win. Nevertheless, these ships proved the Dutch could hold their own against other (presumably) mightier naval powers.",
        ability: "+7 Ranged Strength when attacking defensible Districts. Higher Combat Strength (50 vs. 45). Higher Ranged Strength (60 vs. 55)."
    },
    {
        name: "Hwacha",
        icon: "../imgs/Hwacha.webp",
        description: "The Korean hwacha (or “fire chariot”) launched the most terrifying fireworks display of the 15th Century. At first glance, this simple, two-wheeled wooden cart bears little more than a slotted horizontal board as its cargo. When fully loaded and fired, dozens of rocket-propelled projectiles would streak out from those slots, raining a steel-tipped volley upon distant enemy formations. This efficient death machine came to prominence when it helped repel a late 16th Century Japanese invasion of Korea. The hwacha presence at the Battle of Haengju significantly aided the 3,400 Korean defenders against an invading samurai infantry nine times their size.",
        ability: "Cannot attack after moving unless its maximum Movement is 3 or more. Lower Production cost (250 vs. 330). Lower Combat Strength (45 vs. 50). Lower Gold maintenance cost (3 vs. 5)."
    },
    {
        name: "Janissary",
        icon: "../imgs/Janissary.webp",
        description: "The elite infantry of the Ottoman Empire had a lasting cultural impact within the Ottoman Empire and on the military history of the world at large. The Janissaries embodied many aspects of the Ottoman Empire's systems of governance and warfare, and remain one of the most recognizable military forces in history. At the time they were created in the reign of Murad I, they were a revolutionary military force (the term Janissary literally means “New Soldier”) combining iron discipline, strong esprit de corps, and the latest military weapons. The Ottoman Sultans were entitled to extract a fifth of the value of their territory. Often this took the form of levies of labor or manpower. Christian communities in the Balkans were compelled to provide boys to the Janissaries. The boys were taken from their families and communities, converted to Islam, and then raised in the strict discipline of the Janissary corps. Janissaries were originally forbidden to marry (this stricture was relaxed later) or engage in trade, and swore loyalty to the Sultan himself. The Janissaries had their own distinctive marching bands—the mehter—which influenced European military marches in successive centuries. They were well-paid, and given the special attention of the Sultan, who would appear once a year among his Janissaries to draw his pay. The Janissary corps was strongly meritocratic, and a successful Janissary could retire with a pension and considerable cultural prestige. The Janissaries may have been the first infantry force to be predominately equipped with muskets. They wore uniforms at a time when the practice was still uncommon, with a distinctive high white hat with trailing flap. The Janissaries became one of the most politically-powerful factions within the Ottoman Empire and comparisons to the Praetorian Guard of Rome are apt. However, they resisted most of the efforts to reform their organization, bringing them into conflict with later Sultans. In 1826, the Janissary corps mutinied in response to European-style infantry reforms. Sultan Mahmud II turned cannons on their barracks and executed any Janissary who survived the bombardment. This event was termed the “Auspicious Incident.”",
        ability: "Receives one free Promotion when first trained, purchased, or upgraded from an earlier unit. Can only be trained in cities with a Population of 2 or more. If trained in a city that was founded by the Ottomans, subtracts 1 from its Population. Lower Production cost (120 vs. 240). Higher Combat Strength (60 vs. 55)."
    },
    {
        name: "Malón Raider",
        icon: "../imgs/Malon_Raider.webp",
        description: "The 16th Century brought a Spanish invasion to what is now southern Chile. It also brought horses, which the Mapuche had never seen before encountering the conquistadors. Their presence on the battlefield forced the Mapuche to adjust their tactics. They quickly learned how to use horses, turning one of the greatest Spanish advantages against them. The mounted malón raiders—so named for their retributive attacks on invaders—would launch quick raids to harass an enemy, before leading a responding enemy into an ambush.",
        ability: "+5 Combat Strength within 4 tiles of friendly territory. Pillaging only costs 1 Movement. Ignores enemy zone of control."
    },
    {
        name: "Nau",
        icon: "../imgs/Nau.webp",
        description: "During the 1300s to the 1500s, the Portuguese dominated the seas. Trade networks linked Lisbon and ports across Asia, Africa, and the New World, and reshaped how we see the world today. For instance, without the Portuguese introduction of New World chili peppers to Asia, we would not have spicy Thai food, and without the Portuguese presence in Japan, we would not have tempura (from the Latin quatuor anni tempora – a time of eating no meat). But it was not all spices: nau transported gold, Catholic missionaries… and enslaved persons. The nau was a larger version of the caravel, with square sails in the front, and triangular sails on the mizzenmast. Their heavy build allowed them to navigate stormier seas, especially around the southern tips of Africa and South America, and to reach farther than the caravel or cog.",
        ability: "Receives one free Promotion when first trained, purchased, or upgraded from an earlier unit. Has 2 build charges. Can construct a Feitoria (Consumes a build charge)."
    },
    {
        name: "Sea Dog",
        icon: "../imgs/Sea_Dog.webp",
        description: "Heroic privateers to the English, pirates to everyone else. From 1560 to 1605 AD, Elizabeth I gave permission to her “Sea Dogs” to attack the ships and colonies of other nations – especially the Spanish – at will, usually without the nicety of being at war. The likes of Sir John Hawkins and Sir Francis Drake and Sir Walter Raleigh (in fact, many of these pirates were knighted) raided across the Caribbean and even reached the California coast to ply their bloody trade: grabbing as much treasure as they could for the English crown ... and themselves of course.  In England’s hour of greatest need, the Sea Dogs spearheaded Elizabeth’s defense against the Spanish Armada in 1588. Hawkins is also known as the pioneer of the British slave trade, and Drake took part in the Rathlin Island Massacre of some 600 men, women, and children off the coast of Ireland.",
        ability: "Higher Strength Ranged Strength (55 vs. 50). Can capture defeated enemy naval units. (Does not work for Barbarian or city-state ships.)"
    },
    {
        name: "Winged Hussar",
        icon: "../imgs/Winged_Hussar.webp",
        description: "Polish military reforms of the late 1570s gave birth to the winged hussars, a fearsome heavy cavalry force who would enjoy their elite status for the next two centuries. Rather than fielding cavalry comprised of foreign mercenaries, Transylvanian prince Stephen Bathory (also Grand Duke of Lithuania, King-by-right-of-his-wife of Poland, and collector of increasingly impressive titles) filled the ranks of the winged hussars with Polish nobility and their retinues. The famed 'wings' were wooden frames with feathers attached, borne on a rider's back to clearly distinguish them. It was said the distinctive sound of the wings startled enemy horses and demoralized enemy soldiers with an 'evil hiss'—by novelists of later centuries, who likely romanticized a ceremonial accessory. Far less contentious a question are the lances, sabers, and pistols the winged hussars brought to the battlefield, which no doubt startled enemy horses and demoralized enemy soldiers.",
        ability: "Pushes back enemies if it does more damage than it takes when attacking. Defenders that cannot be pushed back take additional damage."
    },
    {
        name: "Cossack",
        icon: "../imgs/Cossack.webp",
        description: "The kazaki were members of semi-democratic, semi-nomadic, semi-militaristic communities along the steppe-shores of the Dnieper, Don, Ural, Volga and other rivers cutting across the Ukraine. It isn’t clear when these Slavs started settling in the region after the collapse of the Khazar kingdom, but it is likely after the Mongol tide receded, so perhaps late 13th Century AD. A mixture of horse barbarians and “civilized” peoples, by the 1600s the Cossacks were a loose confederation of tribes and independent communes. Internal politics notwithstanding – and the various Cossack hosts fought among themselves as much as against their neighbors – they became a force to be reckoned with, light cavalry par excellence. In time, early 17th Century or so, some of the hosts took service with the growing Russian kingdom to the north, providing a buffer against the Crimean Tatars and Ottomans to the south. The Cossacks would thereafter figure in every war the Russians fought, until virtually annihilated by Stalin following WW2.",
        ability: "+5 Combat Strength when fighting in or next to home territory. Can move after attacking. Higher Production cost (340 vs. 330). Higher Combat Strength (67 vs. 62)."
    },
    {
        name: "Garde Impériale",
        icon: "../imgs/Garde_Imperiale.webp",
        description: "From a small cadre of veterans under the direct command of Napoléon Bonaparte, formed in 1799 from the union of the Guard of the Directory and the Grenadiers of the Legislature (both of those effete democratic bodies soon enough done away with by the emperor), the Garde Impériale grew during the Napoleonic Wars to be a division strong. The Garde was divided into three echelons depending on experience: the Old, the Middle and the Young. Napoleon favored his Garde, giving them higher pay as well as better rations, equipment, and living quarters. Nonetheless, the Old Guard were outspoken in their complaints, often directly to Napoleon himself, earning them the nickname les Grognards (“the grumblers”) among the rest of the French troops. Serving in every campaign during the wars, at Waterloo they were committed in desperation to secure a victory, but the Middle Guard retreated (for the first and only time) under withering fire; the Old Guard and some Young Guard units stood their ground to cover the Emperor’s withdrawal, only to be virtually annihilated by the British and Prussian cannon. Thus came to an inglorious end the most elite (according to the French and to wargame designers) of all military units in history.",
        ability: "Earns Great General points from kills. +10 Combat Strength on the original Capital's home continent. Higher Combat Strength (70 vs. 65)."
    },
    {
        name: "Highlander",
        icon: "../imgs/Highlander.webp",
        description: "In the wake of Scotland’s 1719 Jacobite rising, the British Army recruited loyal Scottish clans (the Campbells, Grants, Frasers, and Munros) to promote unity and keep the peace in the Scottish Highlands. The first of the Highland Regiments was known as the Black Watch thanks to their classic dark tartans—with prominent red waistcoats to show their loyalty to Great Britain. The British Army regulars carried a musket and bayonet into battle. The Highlanders took it a step further by charging into the fray with broadswords, an arguably uncommon weapon for the 18th Century. They first saw combat outside of their homeland at the Battle of Fontenoy (1745), where a French writer described them as “Highland furies” who fought with “more violence than ever did a sea driven by a tempest.” Highlanders continue to serve in modern times, though their broadswords are (presumably) ceremonial.",
        ability: "+5 Combat Strength in Hills and Woods. Exerts zone of control. Higher Combat Strength (50 vs. 45). Higher Ranged Strength (65 vs. 60)."
    },
    {
        name: "Huszár",
        icon: "../imgs/Huszar.webp",
        description: "The Huszár (often spelled “hussar” in Western Europe) are a class of light cavalry, commonly used for reconnaissance and pursuit of routed forces. One of the recurring motifs of warfare in Central and Eastern Europe is the prevalence and effectiveness of light cavalry, and the Huszár is one of the last types of horse cavalry. The term dates to the reign of Matthias Corvinus during the 15th Century, and refers to unarmored riders equipped with lances and shield, but became more generalized to Hungarian and Balkan light cavalry who fought as skirmishers. The word itself is from the Serbian word for “brigand.” Huszárs had highly distinctive uniforms. Their gold-lace fronted jackets are called dolman. Over this they would wear a short cape, called the pelisse. The busby is the large, furry hat. In addition, many Hussars (particularly between the Seven Years' War and the Napoleonic Era) wore their hair long, in elaborate plaits, and favored enormous mustaches in what may once have been a traditional hairstyle but over time simply became part of the panache of the Huszár. In the 19th Century, Hussars were the equivalent of fighter pilots: Dashing, insouciant, sexy, and brave at their best, and borderline-insubordinate, sneering drunks at their worst. Literature of the period uses the hussar as a trope to depict a character as a high-living rogue. It is necessary to distinguish between a traditional hussar and the Polish winged hussar. The latter are armored shock cavalry who fought with lances on the charge. Polish actually uses a different military term for these hussars from more conventional hussars.",
        ability: "+3 Combat Strength for every active Alliance. Higher Combat Strength (65 vs. 62). Higher Production cost (335 vs. 330)."
    },
    {
        name: "Llanero",
        icon: "../imgs/Llanero.webp",
        description: "The Llanos grasslands extend across eastern Colombia and western Venezuela, and are the home of those countries’ brave, hardy cattlemen, the llaneros. Separated from the rich coastal Caribbean ports, the llaneros developed a strong individualistic and resourceful streak, something that won them acclaim when they served as cavalry on both sides of the wars of Latin American independence. Famously, one of their own, José Antonio Páez, formed the llaneros into an effective fighting force, especially when facing down the similarly-organized royalist llaneros of José Tomás Boves. The llanero culture came as Spanish settlers lived near and intermingled with indigenous groups, creating a new, distinctive society with its own music, cuisine, and, especially, its own tradition of horsemanship. Owing to their dislike for the coastal elites, llaneros initially were persuaded to fight for the Crown, but under Páez, the llaneros became a potent force for independence, leading the revolutionaries to victory in the battles of Boyacá and Carabobo. In one memorable scene, Páez led his llaneros through a burning plain, stunning the Spanish, who had been disorientated by the flames and smoke… and the thunder of thousands of horses galloping straight for them!",
        ability: "+2 Combat Strength for each adjacent Llanero. Regains all HP when in range of a Comandante General that uses its retire ability. Lower Gold maintenance cost (2 vs. 5)."
    },
    {
        name: "Minas Geraes",
        icon: "../imgs/Minas_Geraes.webp",
        description: "Intended to be the first step in Brazil becoming an international power, the Minas Geraes-class were two battleships of 11,800-tons launched in the early 20th Century. While these didn’t do much in making Brazil a power to be reckoned with, the Minas Geraes and sister ship São Paulo did start a South American naval arms race, and caused quite a stir in the United States and United Kingdom (who weren’t real keen on having battleships in South American waters that weren’t theirs). The design plans for the new class took two years to complete, and then were tossed when the new HMS Dreadnought launched in 1906 made them obsolete. Finally the keels of the new design were laid down, and in September 1908 the Minas Geraes launched, followed by the São Paulo in 1909. Their careers weren’t much to speak of – centerpieces in suppressing a naval mutiny and a couple of rebellions. And they met an ignominious end; the Minas Geraes was scrapped in 1950, and the São Paulo sank en route to the scrapyard in 1951.",
        ability: "Higher Combat Strength (70 vs. 60). Higher Ranged Strength (80 vs. 70). Higher Anti-Air strength (95 vs. 90)."
    },
    {
        name: "Redcoat",
        icon: "../imgs/Redcoat.webp",
        description: "The red (or, more accurately, the shade rose madder) coat of the British infantry evolved from the ceremonial uniforms of the early 1600s; it was officially adopted in February 1645 AD when Parliament drafted the regulations for the New Model Army, with the 12 regiments of foot all wearing red coats with different colored facings to distinguish between them. For the next quarter-millennia most of the British infantry wore such, making them splendid targets among the trees, dunes, jungles and hills of the Empire. The rationale for such a choice was that (despite the fiction it was because bloodstains were disheartening for the men) red coats were instantly identifiable on the field in an age prior to use of smokeless powder, where battlefield visibility was a greater problem than tactical concealment. This choice of uniform hence helped maintain order, combat efficiency and morale (although not all British forces would use red uniforms). The term “redcoat” became a source of pride for the British, and a curse word for just about everyone else.",
        ability: "No Movement cost to disembark. +10 Strength when fighting on a continent other than the English Capital's. Higher Combat Strength (70 vs. 65)."
    },
    {
        name: "Rough Rider",
        icon: "../imgs/Rough_Rider.webp",
        description: "The First United States Volunteer Cavalry – better known to the unenlightened as the “Rough Riders” (the nickname taken from Buffalo Bill’s “Congress of Rough Riders of the World” … and describing Teddy’s unruly recruits rather well) – was a regiment raised by Theodore Roosevelt in 1898 AD for action in the Spanish–American War. Roosevelt had been a staunch supporter of America acquiring a colonial empire by almost any means, and when troubles arose in Cuba the United States took advantage of the opportunity to beat up the moribund and bankrupt Spanish Empire. Roosevelt immediately resigned his post as Asst. Secretary of the Navy and raised a volunteer regiment of 1060 cowboys, ranchers, miners, college athletes, and other rough sorts from Arizona, New Mexico, Texas, and Oklahoma. Although a cavalry unit, they served with distinction – mostly afoot, as at the famous charge up San Juan Hill (actually, Kettle Hill – but that’s Americans abroad for you) on July 1. Afterward the Rough Riders were part of the siege of Santiago, until Spain surrendered in August, whereupon the volunteers returned home and went about celebrating in their own ways.",
        ability: "Earns Culture from kills on its Capital's continent. +10 Combat Strength when fighting on Hills. Higher Combat Strength (67 vs. 64). Higher Movement (5 vs. 4). Lower Gold maintenance cost (2 vs. 5). No strategic resource requirement. Higher Production cost (385 vs. 330)."
    },
    {
        name: "Digger",
        icon: "../imgs/Digger.webp",
        description: "At the onset of World War I, the British Army's need for soldiers led to the creation of the Australian Imperial Force. For bureaucratic ease, these troops were combined into a corps alongside soldiers from New Zealand. The newly formed corps underwent a baptism of enemy fire at the Battle of Gallipoli, which began with the (then) largest amphibious landing in the modern era. Called 'Diggers' for their rapid entrenchment—or by their British comrades who thought all Australians worked in mines—they distinguished themselves until the war's armistice, gaining a courageous and genial reputation despite many hardships. Dissolved after the war's end, the Diggers have been re-formed when Australian and New Zealand troops fight together in larger-scale conflicts (such as World War II and Vietnam).",
        ability: "+10 Combat Strength on coastal tiles. +5 Combat Strength outside Australian territory. Higher Combat Strength (78 vs. 75). No strategic resource requirement."
    },
    {
        name: "Mountie",
        icon: "../imgs/Mountie.webp",
        description: "The Royal Canadian Mounted Police are a law enforcement body, not a military unit (sorry!), and were originally created to help establish the law in the Canadian frontier. Their distinctive dress uniform of Red Serge jacket, campaign hat, and Strathcona boots are universally recognized and one of the enduring images of Canada. They are courteous, disciplined, professional, and they always get their man. In 1873, Parliament of Canada established the North-West Mounted Police, sending 150 recruits into Manitoba, including the legendary Sam Steele, who would go on to become Superintendent of the NWMP and one of Canada's greatest heroes. Wilfrid Laurier wanted to disband the growing NWMP, but the discovery of gold in the Klondike and the subsequent gold rush proved the need for law enforcement in the frontier. Eight Mounties were killed during the North-West Rebellion. King Edward VII awarded the NWMP the Royal title in 1904. In 1919, the Mounties were merged with the Dominion Police, which were an Eastern Canadian federal police force, and the organization was renamed the Royal Canadian Mounted Police. It is difficult to conceive of the immense size of the territory that a relatively small band of Mounties would patrol. Whether shutting down illegal whiskey distilling, or negotiating with bands of First Nations, or pursuing criminals beyond the far fringes of civilization, the Mounties were often the only government presence in the frontiers. Their isolation meant that they needed to build support with the people of that land, and in this they were widely praised. The First Nations especially had a far more positive relationship with the Mounties than any US police or military force. Today the Mounties are one of the best-equipped and flexible law enforcement units in the world. Although the last dogsled patrol ended in 1969, they still serve as the representatives of the government and the defenders of justice. And today, as since 1873, they always get their man.",
        ability: "Has Sight Sight of 4. +5 Combat Strength when within 2 tiles of a National Park. +5 additional Combat Strength if the park is Canadian. Ignores enemy zone of control."
    },
    {
        name: "U-Boat",
        icon: "../imgs/U-Boat.webp",
        description: "The 'Unterseeboot' – U-boat – struck fear, and anger, in the hearts of Germany’s enemies during two world wars. The first German-built submarine, the 26-foot long Brandtaucher (“fire-diver”), sank during its initial test dive in the harbor at Kiel. This was followed by several submersibles built in Germany, which were sold to the Greeks, Ottomans, and Russians (all had rather ignominious careers). Finally the Germans got it right; the U-19 – they finally quit giving the boats names – was launched in 1912 with two-stroke diesel engines, four torpedo tubes and two deck guns, and able to dive to 164 feet. At the opening of WW1, Germany had 28 U-boats in service; in the first ten weeks, these sank five British cruisers. So effective were the U-boats that the Treaty of Versailles forbade the construction of German submarines. But, the U-boat fleet was rebuilt, and by the end of WW2 the boats had sunk some 2779 ships (confirmed) totaling 14.1 million tons – roughly 70% of Allied losses in all theaters. In 1955 West Germany was allowed to have a navy again ... and promptly started building U-boats, the latest being the non-nuclear U-35, commissioned in March 2015.",
        ability: "+10 Combat Strength when fighting on Ocean tiles. Higher Sight (3 vs. 2). Lower Production cost (430 vs. 480). No strategic resource requirement."
    },
    {
        name: "P-51 Mustang",
        icon: "../imgs/P-51_Mustang.webp",
        description: "With the coming of WW2, it was quickly apparent that America’s fighter aircraft were obsolete and not-up-to-snuff against the German and Japanese fighters, so the United States sold the old planes to the British and Russians and developed the P-51 “Mustang.” Designed to specifications supplied by the British Purchasing Commission as a long-range, high-altitude, single-seat fighter and fighter-bomber and bomber escort – able to outperform the best Luftwaffe fighters above 15,000 feet and outlast the Japanese fighters – the prototype was unveiled in September 1940. By 1943, Mustangs were in service on every American front, knocking the enemy out of the skies with abandon. Even with the advent of jet fighters, the old warbird served during the Korean War as a fighter-bomber. Afterward, those that weren’t scrapped were sold as surplus, most of which were converted for the obscure sport of air racing or restored for the obscure spectacle of air shows.",
        ability: "+5 Combat Strength against fighter aircraft. Gains 50% more experience. Higher Combat Strength (105 vs. 100) and Ranged Strength (105 vs. 100). Higher Movement (10 vs. 8)."
    }
]

const seedUnits = () => Unit.bulkCreate(unitData)

module.exports = seedUnits